# Packages

In [45]:
import numpy as np
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import plotly
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from datetime import datetime, timedelta, date
import math
import os
from pathlib import Path
import re
import gc
from tqdm import tqdm

import statsmodels.formula.api as smf
import statsmodels.api as sm
from statsmodels.graphics.tsaplots import plot_pacf

import scipy.stats as stats
from sklearn.model_selection import train_test_split, TimeSeriesSplit
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.decomposition import PCA
from sklearn.preprocessing import RobustScaler, LabelEncoder, OrdinalEncoder

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)
pd.set_option('display.float_format', lambda x: "%.4f" % x)
pd.options.plotting.backend = "plotly"

plt.style.use('ggplot')
sns.set_style('darkgrid')

In [46]:
# helper functions
def get_info(df):
    missing_values_train = pd.DataFrame({'Feature': df.columns,
                              'No. of Missing Values': df.isnull().sum().values,
                              '% of Missing Values': ((df.isnull().sum().values)/len(df)*100)})

    unique_values = pd.DataFrame({'Feature': df.columns,
                                'No. of Unique Values': df.nunique().values})

    feature_types = pd.DataFrame({'Feature': df.columns,
                                'DataType': df.dtypes})

    merged_df = pd.merge(missing_values_train, unique_values, on='Feature', how='left')
    merged_df = pd.merge(merged_df, feature_types, on='Feature', how='left')

    return merged_df

def reduce_memory_usage(df: pd.DataFrame, verbose=False) -> pd.DataFrame:
    start_mem = df.memory_usage(deep=True).sum() / 1024**2
    if verbose:
        print(f"Memory usage before: {start_mem:.2f} MB")
    
    for col in df.columns:
        col_type = df[col].dtype
        
        if col_type == 'float64':
            df[col] = pd.to_numeric(df[col], downcast='float')
        elif col_type == 'int64':
            df[col] = pd.to_numeric(df[col], downcast='integer')
    
    end_mem = df.memory_usage(deep=True).sum() / 1024**2
    if verbose:
        print(f"Memory usage after: {end_mem:.2f} MB")
        print(f"Reduced by {(start_mem - end_mem) / start_mem * 100:.1f}%")
    
    return df

# Pulling Data

## New Jersey

In [47]:
nj_path = "./data/NewJersey/nj_data.csv"
nj_df = pd.read_csv(nj_path, encoding='latin-1')
nj_df = reduce_memory_usage(nj_df, verbose=True)
print(nj_df.shape)
nj_df.head()

/var/folders/8r/qgk4_l1j20gfq28wvs_pxh2r0000gn/T/ipykernel_4510/3470814138.py:2: DtypeWarning: Columns (0: Officer In Uniform) have mixed types. Specify dtype option on import or set low_memory=False.
  nj_df = pd.read_csv(nj_path, encoding='latin-1')

Memory usage before: 226.74 MB
Memory usage after: 225.08 MB
Reduced by 0.7%
(96688, 46)

,Form ID,County,Agency Name,Officer Name,User ID,Incident ID,Report Number,Incident Case Number,Incident Date,Other Officer Involved,Officer In Uniform,Incident Municipality,Indoor Or Outdoor,Incident Weather,Video Footage,Video Type,Incident Lighting,Location Type,Incident Type,Contact Origin,Planned Contact,Officer Age,Officer Race/Ethnicity,Officer Rank,Officer Gender,Officer Injury Type,Officer Injuries Injured,Officer Medical Treatment,Officer Hospital Treatment,Total Sub Injured In Incident,Subject Injured In Incident,Subject Injured Prior To Incident,Perceived Condition Of Subject,Subject Actions,Subject Resistance,Subject Medical Treatment,Subject Injury Type,Subject Arrested,Reason Subject Not Arrested,Subject Type,Subject Age,Subject Race/Ethnicity,Subject Gender,Force Type,Incident Year,KEEP/DROP
0,866515,Ocean,Berkeley Twp PD,Michael Bulwinski,10818.0000,OCEAN-BERKELEY TWP PD-23-003647,UOF23-11-52,23-003647,11/6/2023,Not Provided,True,"Berkeley, Ocean County",Outdoors,Clear,Yes,Body Worn,Darkness,Street,Assault,Dispatched,NaN,33,White,Officer,Male,Not injured,FALSE,NaN,NaN,0.0000,No,Unknown,No unusual condition noted,Attempt to escape from Custody,Passive Resistor,NaN,NaN,TRUE,NaN,Person,28,Hispanic,Male,Used take down on,2023,KEEP
1,91681,Ocean,Toms River Twp PD,Frank Moschella,11497.0000,OCEAN-TOMS RIVER TWP PD-21-20078,UOF21-5-48,21-20078,5/13/2021,TRUE,True,"Dover, Ocean County",Indoors,Clear,Yes,Motor Vehicle,Dawn/Dusk,Business,"Welfare Check, Potential Mental Health Incident",Officer Dispatched,NaN,34,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,No,Potential Mental Health Incident,"Resisted arrest/police officer control, Verbal...","Verbal, Resistive tension (stiffening, tigheni...",NaN,NaN,FALSE,Medical/Mental Health Incident,Person,55,White,Female,Used arms,2021,KEEP
2,50307,Cumberland,Vineland PD,Derrick Magee,4387.0000,CUMBERLAND-VINELAND PD-2021-4288,UOF21-1-19,2021-4288,1/27/2021,TRUE,True,"Vineland, Cumberland County",Outdoors,Clear,Yes,Body Worn,Artificial,Other,MV/Traffic Stop,Officer Initiated,NaN,30,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,1.0000,Yes,No,No unusual condition noted,"Resisted arrest/police officer control, Attack...","Resistive tension (stiffening, tighening muscl...","EMS on scene, Hospital",Abrasion/Laceration/Puncture,TRUE,NaN,Person,37,Hispanic,Male,Canine bit (apprehension),2021,KEEP
3,201634,Ocean,Lakewood PD,Deon Smith,11159.0000,OCEAN-LAKEWOOD PD-22-001779,UOF22-1-9,22-001779,1/8/2022,Not Provided,True,"Lakewood, Ocean County",Indoors,NaN,Yes,Body Worn,Artificial,Hospital,Medical Emergency,Dispatched,NaN,28,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,No,Other unusual condition noted,"Strike with open hand, fist, or elbow",Active Resistor,NaN,NaN,FALSE,Medical/Mental Health Incident,Person,35,Hispanic,Female,Used arms/hands,2022,KEEP
4,1594362,Bergen,Rutherford PD,Michael Merli,7316.0000,BERGEN-RUTHERFORD PD-25-08463,UOF25-5-1,25-08463,5/11/2025,Not Provided,True,"Rutherford, Bergen County",Indoors,NaN,Yes,"Body Worn, CED Camera",Artificial,Business,Theft/Shoplifting,Dispatched,NaN,47,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,No,No unusual condition noted,Attempt to escape from Custody,Active Resistor,NaN,NaN,TRUE,NaN,Person,19,Hispanic,Male,Used take down on,2025,KEEP

In [48]:
nj_df["Incident Case Number"].value_counts()

Incident Case Number
24-29560      24
25-031332     16
2024-02894    15
22-033415     15
20-080948     14
              ..
2025-2758      1
C2043822       1
25-011543      1
P250372236     1
C22040458      1
Name: count, Length: 51743, dtype: int64

In [49]:
nj_df[lambda x: x["Incident Case Number"] == "24-29560"]

,Form ID,County,Agency Name,Officer Name,User ID,Incident ID,Report Number,Incident Case Number,Incident Date,Other Officer Involved,Officer In Uniform,Incident Municipality,Indoor Or Outdoor,Incident Weather,Video Footage,Video Type,Incident Lighting,Location Type,Incident Type,Contact Origin,Planned Contact,Officer Age,Officer Race/Ethnicity,Officer Rank,Officer Gender,Officer Injury Type,Officer Injuries Injured,Officer Medical Treatment,Officer Hospital Treatment,Total Sub Injured In Incident,Subject Injured In Incident,Subject Injured Prior To Incident,Perceived Condition Of Subject,Subject Actions,Subject Resistance,Subject Medical Treatment,Subject Injury Type,Subject Arrested,Reason Subject Not Arrested,Subject Type,Subject Age,Subject Race/Ethnicity,Subject Gender,Force Type,Incident Year,KEEP/DROP
6768,1089375,Hudson,Hoboken PD,David Chicara,222981.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-92,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,Clear,Yes,Body Worn,Artificial,Hospital,Assisting another officer,Dispatched,NaN,28,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,Under influence of alcohol/drugs/both,"Resisted arrest/police officer control, Attemp...",Active Assailant,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
28193,1090120,Hudson,Hoboken PD,Nasir Willey,362175.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-101,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,Clear,Yes,Body Worn,Artificial,Hospital,"Assisting another officer, Assault",Dispatched,NaN,21,Not Provided,Not Provided,Other,Complaint of pain,TRUE,Hospital,Treated and Released,0.0000,No,Yes,No unusual condition noted,"Resisted arrest/police officer control, Attemp...",Active Assailant,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
29643,1090660,Hudson,Hoboken PD,Ramon Calderon,18648.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-106,24-29560,4/27/2024,Not Provided,True,"Hoboken, Hudson County","Indoors, Outdoors",Clear,Yes,Body Worn,Darkness,"Street, Police Station","Assault, Disturbance (drinking, fighting, diso...",Citizen Initiated,NaN,48,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,1.0000,Yes,No,"Other unusual condition noted, Under influence...","Attempt to commit crime, Attempt to self-harm,...","Threatening Assailant, Active Assailant, Activ...",Hospital,Complaint of pain,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
33384,1090125,Hudson,Hoboken PD,Joshua Campoverde,18655.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-102,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,Clear,Yes,Body Worn,Artificial,Hospital,"MV/Traffic Stop, Assault, Possession of CDS, T...",Dispatched,NaN,28,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,No unusual condition noted,"Biting, Attempt to self-harm, Prevent harm to ...",Active Assailant,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
43565,1089316,Hudson,Hoboken PD,Alexander Miller,362179.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-90,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,NaN,Yes,"Body Worn, Station House",Artificial,Police Station,"Assault, Assisting another officer",Dispatched,NaN,30,White,Officer,Male,Not injured,FALSE,NaN,NaN,1.0000,Yes,Yes,No unusual condition noted,"Attempt to self-harm, Resisted arrest/police o...",Active Assailant,Hospital,"Contusion/bruise, Abrasion/Laceration/Puncture",TRUE,NaN,Person,36,Black or African American,Male,Used take down on,2024,KEEP
47527,1090129,Hudson,Hoboken PD,Tyler Soto,18668.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-103,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,Clear,Yes,"Body Worn, Station House",Artificial,Police Station,Assault,Dispatched,NaN,35,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,1.0000,Yes,Yes,No unusual condition noted,"Resisted arrest/police officer control, Attemp...",Active Assailant,Hospital,"Abrasion/Laceration/Puncture, Contusion/bruise",TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
48305,1089432,Hudson,Hoboken PD,Michael Straten,18671.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-94,24-29560,4/27/2024,Not Provided,True,"Hoboken, Hudson County",Outdoors,Clear,Yes,"Body Worn, Residential/Home",Artificial,Street,"Assault, Subject with other weapon",Dispatched,NaN,29,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,1.0000,Yes,No,Under influence of alcohol/drugs/both,"Attempt to self-harm, Resisted arrest/police o...",Active Assailant,Hospital,Abrasion/Laceration/Puncture,TRUE,NaN,Person,36,Black or African American,Male,Used pressure points on,2024,KEEP
48514,1090118,Hudson,Hoboken PD,Joshua Campoverde,18655.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-100,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County","Indoors, Outdoors",Clear,Yes,Body Worn,Artificial,Police Station,"Assault, Assisting another officer",Dispatched,NaN,28,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,No unusual condition noted,"Attempt to self-harm, Biting, Resisted arrest/...",Active Assailant,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
48763,1089369,Hudson,Hoboken PD,David Chicara,222981.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-91,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,Clear,Yes,"Body Worn, Station House",Artificial,Police Station,"Assisting another officer, Terroristic Threats...",Dispatched,NaN,28,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,Under influence of alcohol/drugs/both,Resisted arrest/police officer control,Active Assailant,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
52239,1089946,Hudson,Hoboken PD,Michael Costello,18705.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-97,24-29560,4/27/2024,Not Provided,True,"Hoboken, Hudson County","Indoors, Outdoors",Clear,Yes,"Body Worn, Station House","Darkness, Artificial","Street, Police Station, Hospital","Assault, Subject with other weapon, MV Acciden...",Dispatched,NaN,47,Not Provided,Not Provided,Other,Complaint of pain,TRUE,Hospital,Treated and Released,1.0000,Yes,No,No unusual condition noted,"Attempt to self-harm, Prevent harm to another,...",Active Assailant,Hospital,"Contusion/bruise, Abrasion/Laceration/Puncture",TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
52684,1089943,Hudson,Hoboken PD,Jaydan Gonzalez,362178.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-96,24-29560,4/27/2024,Not Provided,True,"Hoboken, Hudson County","Outdoors, Indoors",Clear,Yes,"Body Worn, Station House","Artificial, Darkness","Street, Police Station","Assault, Subject with other weapon, MV Acciden...",Officer Initiated,NaN,23,Not Provided,Not Provided,Other,Complaint of pain,TRUE,"Hospital, EMS on scene",Treated and Released,1.0000,Yes,No,No unusual condition noted,"Attempt to self-harm, Resisted arrest/police o...",Active Assailant,Hospital,"Contusion/bruise, Abrasion/Laceration/Puncture",TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
57817,1089433,Hudson,Hoboken PD,Jessica Pizanie,183204.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-95,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County","Indoors, Outdoors",Clear,Yes,Body Worn,Daylight,Hospital,Not Provided,Pre-Planned Contact,Prisoner Transfer,34,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,Under influence of alcohol/drugs/both,Resisted arrest/police officer control,Active Assailant,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Compliance hold with impact weapon- not a strike,2024,KEEP
59280,1089167,Hudson,Hoboken PD,Jonathan Butler,18723.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-84,24-29560,4/27/2024,Not Provided,True,"Hoboken, Hudson County","Outdoors, Indoors",Cloudy,Yes,Body Worn,"Darkness, Artificial",Police Station,Assisting another officer,Officer Initiated,NaN,51,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,Under influence of alcohol/drugs/both,"Resisted arrest/police officer control, Biting...",Active Assailant,NaN,NaN,TRUE,NaN,Person,36,Hispanic,Male,Used arms/hands,2024,KEEP
59687,1089389,Hudson,Hoboken PD,Nathaniel Arocho,18748.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-93,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County","Indoors, Outdoors",Clear,Yes,Body Worn,Daylight,Hospital,Not Provided,Pre-Planned Contact,Prisoner Transfer,33,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Unknown,Potential Mental Health Incident,"Resisted arrest/police officer control, Attemp...","Active Resistor, Active Assailant",NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
68898,1090099,Hudson,Hoboken PD,Nasir Willey,362175.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-99,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County","Indoors, Outdoors",Clear,Yes,"Body Worn, Station House",Artificial,Police Station,Assisting another officer,Dispatched,NaN,21,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,No unusual condition noted,"Resisted arrest/police officer control, Preven...",Active Assailant,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
70634,1089953,Hudson,Hoboken PD,Christopher Barral,18650.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-98,24-29560,4/27/2024,Not Provided,True,"Hoboken, Hudson County",Outdoors,Clear,Yes,"Body Worn, Station House","Artificial, Darkness",Street,"Assault, Subject with other weapon, MV Acciden...",Officer Initiated,NaN,34,Not Provided,Not Provided,Other,Complaint of pain,TRUE,"EMS on scene, Hospital",Treated and Released,1.0000,Yes,No,No unusual condition noted,"Attempt to self-harm, Prevent harm to another,...",Active Assailant,Hospital,"Abrasion/Laceration/Puncture, Contusion/bruise",TRUE,NaN,Person,36,Black or African American,Male,"Used arms/hands, Used fists/punch",2024,KEEP
72504,1089221,Hudson,Hoboken PD,Joshua Campoverde,18655.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-88,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,Clear,Yes,Body Worn,Artificial,"Police Station, Hospital","MV/Traffic Stop, Assault, Terroristic Threats,...",Dispatched,NaN,28,Hispanic,Officer,Male,Not injured,FALSE,NaN,NaN,1.0000,Yes,Yes,No unusual condition noted,"Attempt to commit crime, Resisted arrest/polic...",Active Assailant,Hospital,"Contusion/bruise, Abrasion/Laceration/Puncture",TRUE,NaN,Person,36,Black or African American,Male,Used take down on,2024,KEEP
77318,1091804,Hudson,Hoboken PD,Anthony Ingraffia,337577.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-108,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,Clear,Yes,Body Worn,Artificial,Hospital,"Assault, Assisting another officer",Dispatched,NaN,26,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,Under influence of alcohol/drugs/both,"Resisted arrest/police officer control, Threat...",Active Assailant,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
80067,1090150,Hudson,Hoboken PD,Alexander Miller,362179.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-104,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,Clear,Yes,"Body Worn, Station House",Artificial,Police Station,"Assault, Assisting another officer",Dispatched,NaN,30,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,No unusual condition noted,"Attempt to self-harm, Prevent harm to another,...",Active Assailant,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
83045,1089216,Hudson,Hoboken PD,Nasir Willey,362175.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-87,24-29560,4/28/2024,Not Provided,False,"Hoboken, Hudson County","Indoors, Outdoors",Clear,Yes,"Body Worn, Station House","Darkness, Artificial",Street,Assisting another officer,Dispatched,NaN,21,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,No unusual condition noted,Resisted arrest/police officer control,Active Resistor,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
84185,1089259,Hudson,Hoboken PD,Anthony Ingraffia,337577.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-89,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County","Outdoors, Indoors",Clear,Yes,Body Worn,"Darkness, Artificial","Street, Police Station",Assisting another officer,Dispatched,NaN,26,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,Under influence of alcohol/drugs/both,Resisted arrest/police officer control,Active Resistor,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
88111,1089215,Hudson,Hoboken PD,David Chicara,222981.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-86,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Outdoors,Clear,Yes,"Body Worn, Station House",Darkness,"Street, Police Station","Assisting another officer, Assault",Dispatched,NaN,28,Hispanic,Officer,Male,Not injured,FALSE,NaN,NaN,0.0000,No,Yes,No unusual condition noted,Resisted arrest/police officer control,Active Resistor,NaN,NaN,TRUE,NaN,Person,36,Black or African American,Male,Used legs/kicks,2024,KEEP
89464,1089213,Hudson,Hoboken PD,Remy Garcia-Marte,215466.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-85,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,Clear,Yes,"Body Worn, Station House",Artificial,Police Station,Assault,Officer Initiated,NaN,30,Not Provided,Not Provided,Other,Not injured,FALSE,NaN,NaN,1.0000,Yes,Yes,No unusual condition noted,"Prevent harm to another, Resisted arrest/polic...",Active Assailant,Hospital,Abrasion/Laceration/Puncture,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP
93731,1090163,Hudson,Hoboken PD,Tyler Soto,18668.0000,HUDSON-HOBOKEN PD-24-29560,UOF24-4-105,24-29560,4/28/2024,Not Provided,True,"Hoboken, Hudson County",Indoors,Clear,Yes,Body Worn,Artificial,Hospital,"Assault, Possession of CDS, Subject with other...",Citizen Initiated,NaN,35,Not Provided,Not Provided,Other,"Complaint of pain, Contusion/bruise",TRUE,Hospital,Treated and Released,1.0000,Yes,Yes,No unusual condition noted,"Attempt to self-harm, Prevent harm to another,...",Active Assailant,Hospital,Complaint of pain,TRUE,NaN,Person,36,Black or African American,Male,Used arms/hands,2024,KEEP

In [50]:
nj_df[nj_df["Subject Gender"].str.contains(",", regex=False)].head().T

,54,179,193,325,396
Form ID,1671580,164927,1220844,1315411,844380
County,Union,Morris,Mercer,Bergen,Bergen
Agency Name,Roselle PD,Hanover Twp PD,Trenton PD,Fort Lee PD,Fair Lawn PD
Officer Name,Bruno Felicia,Robert Carpenter,Matthew Lupinacci,Doglas Pichardo,Matthew Hearon
User ID,224205.0000,26937.0000,190327.0000,474103.0000,128796.0000
Incident ID,UNION-ROSELLE PD-2025-121390,MORRIS-HANOVER TWP PD-21-28256,MERCER-TRENTON PD-24-008761,BERGEN-FORT LEE PD-I-2024-053068,BERGEN-FAIR LAWN PD-23-15552
Report Number,UOF25-7-86,UOF21-11-18,UOF24-8-287,UOF24-10-56,UOF23-10-12
Incident Case Number,2025-121390,21-28256,24-008761,I-2024-053068,23-15552
Incident Date,7/8/2025,10/28/2021,8/5/2024,10/17/2024,10/19/2023
Other Officer Involved,Not Provided,TRUE,Not Provided,Not Provided,Not Provided
Officer In Uniform,True,True,True,True,True
Incident Municipality,"Roselle, Union County","Hanover, Morris County","Trenton, Mercer County","Fort Lee, Bergen County","Fair Lawn, Bergen County"
Indoor Or Outdoor,Outdoors,"Indoors, Outdoors",Outdoors,Indoors,Outdoors
Incident Weather,Cloudy,Clear,Clear,Clear,Clear
Video Footage,Yes,Yes,Yes,Yes,Yes
Video Type,"Body Worn, Residential/Home",Body Worn,Body Worn,Body Worn,"Body Worn, Motor Vehicle"
Incident Lighting,Daylight,"Artificial, Daylight",Artificial,Artificial,Artificial
Location Type,Street,Business,Street,Residence,Street
Incident Type,"Disturbance (drinking, fighting, disorderly)","Welfare Check, Other",Subject with a gun,Robbery,"MV/Traffic Stop, Eluding, Possession of CDS"
Contact Origin,Dispatched,Officer Dispatched,Dispatched,Officer Initiated,Officer Initiated
Planned Contact,NaN,NaN,NaN,NaN,NaN
Officer Age,44,40,26,25,29
Officer Race/Ethnicity,Not Provided,White,Not Provided,Hispanic,Not Provided
Officer Rank,Not Provided,Sgt.,Not Provided,Officer,Not Provided
Officer Gender,Other,Male,Other,Male,Other
Officer Injury Type,Not injured,Not injured,Not injured,Not injured,Not injured
Officer Injuries Injured,FALSE,FALSE,FALSE,FALSE,FALSE
Officer Medical Treatment,NaN,NaN,NaN,NaN,NaN
Officer Hospital Treatment,NaN,NaN,NaN,NaN,NaN
Total Sub Injured In Incident,0.0000,0.0000,0.0000,0.0000,0.0000
Subject Injured In Incident,"No, No, No, No","No, No","No, Unknown",No,"No, No"
Subject Injured Prior To Incident,"Unknown, Unknown, Unknown, Unknown","No, No","No, No",No,"No, No"
Perceived Condition Of Subject,"No unusual condition noted, No unusual conditi...","No unusual condition noted, Under influence of...","No unusual condition noted, No unusual conditi...","No unusual condition noted, No unusual conditi...","No unusual condition noted, Under influence of..."
Subject Actions,"Strike with open hand, fist, or elbow, Strike ...",Attempt to escape from Custody,"Attempt to commit crime, Attempt to escape fro...","Attempt to escape from Custody, Resisted arres...","Attempt to escape from Custody, Attempt to esc..."
Subject Resistance,"Active Assailant, Active Assailant, Active Ass...",Attempt to flee,"Active Resistor, Active Resistor","Active Resistor, Active Resistor","Passive Resistor, Passive Resistor"
Subject Medical Treatment,NaN,NaN,NaN,NaN,NaN
Subject Injury Type,NaN,NaN,NaN,NaN,NaN
Subject Arrested,"False, False, False, False","True, True","True, True","True, True","False, True"
Reason Subject Not Arrested,Insufficient Probable Cause-includes continuin...,NaN,NaN,NaN,No Probable Cause- Crime Unfounded
Subject Type,"Person, Person, Person, Person","Person, Person","Person, Person","Person, Person","Person, Person"
Subject Age,"18, 18, Under 18, Under 18","38, 65","18, 21","27, 67","23, 38"
Subject Race/Ethnicity,"Black or African American, Black or African Am...","White, White","Black or African American, Black or African Am...","White, White","Hispanic, White"
Subject Gender,"Female, Female, Female, Female","Female, Male","Male, Male","Male, Male","Female, Male"
Force Type,"Discharged Chemical at, Discharged Chemical at...","Used arm bar on, Used arms, Used arms, Used ta...","Used pressure points on, Used pressure points on",Used arms/hands,"Pointing Firearm, Pointing Firearm, Used arms/..."
Incident Year,2025,2021,2024,2024,2023
KEEP/DROP,KEEP,KEEP,KEEP,KEEP,KEEP

In [51]:
for col in ["Subject Gender", "Subject Race/Ethnicity", "Subject Age", "Subject Injured Prior To Incident", 
            "Perceived Condition Of Subject", "Subject Actions", "Subject Resistance", "Subject Arrested", "Force Type"]:
    print(f"{col} : {nj_df[nj_df[col].str.contains(",", regex=False)].shape}")

Subject Gender : (1030, 46)
Subject Race/Ethnicity : (1030, 46)
Subject Age : (1030, 46)
Subject Injured Prior To Incident : (1847, 46)
Perceived Condition Of Subject : (12120, 46)
Subject Actions : (51047, 46)
Subject Resistance : (35252, 46)
Subject Arrested : (1030, 46)
Force Type : (12329, 46)

In [52]:
def expand_nj_subjects(df, delim=','):
    """
    For rows where multiple subjects are encoded with , as a delimiter,
    split into one row per subject.
    
    Subject Race/Ethnicity and Subject Gender are the anchors — the number
    of tokens they produce (split by |) defines how many rows a record expands to.
    
    For Subject Age, Subject Injured Prior To Incident, Perceived Condition Of Subject, Subject Actions, Subject Resistance, Subject Arrested:
      - if the column has the same number of |-delimited tokens as the anchor, split them too
      - otherwise, carry the original value into every expanded row
    """
    anchor_cols = ["Subject Race/Ethnicity", "Subject Gender"]
    conditional_cols = [
        "Subject Age", "Subject Injured In Incident", "Subject Injured Prior To Incident", 
        "Perceived Condition Of Subject", "Subject Actions", 
        "Subject Resistance", "Subject Arrested", 
        "Subject Medical Treatment", "Subject Injury Type"
    ]

    expanded_rows = []

    for idx, row in df.iterrows():
        # Split anchors by deliminiator
        race_val = row[anchor_cols[0]]
        gender_val = row[anchor_cols[1]]

        race_tokens = [t.strip() for t in str(race_val).split(delim)] if pd.notna(race_val) else [race_val]
        gender_tokens = [t.strip() for t in str(gender_val).split(delim)] if pd.notna(gender_val) else [gender_val]

        n = len(gender_tokens)

        # If gender token count mismatches race, broadcast gender to all rows
        if len(race_tokens) != n:
            race_tokens = [race_val] * n

        # Pre-split conditional columns
        cond_splits = {}
        for col in conditional_cols:
            val = row[col]
            if pd.notna(val):
                tokens = [t.strip() for t in str(val).split(delim)]
                cond_splits[col] = tokens if len(tokens) == n else None
            else:
                cond_splits[col] = None

        for i in range(n):
            new_row = row.copy()
            new_row[anchor_cols[0]] = race_tokens[i]
            new_row[anchor_cols[1]] = gender_tokens[i]

            for col in conditional_cols:
                if cond_splits[col] is not None:
                    new_row[col] = cond_splits[col][i]
                # else: leave original broadcast value as-is

            expanded_rows.append(new_row)

    return pd.DataFrame(expanded_rows).reset_index(drop=True)


print("nj_df shape before expansion:", nj_df.shape)
nj_df = expand_nj_subjects(nj_df)
print("nj_df shape after expansion:", nj_df.shape)

nj_df shape before expansion: (96688, 46)
nj_df shape after expansion: (97877, 46)

## Ohio

In [53]:
ohio_path = './data/Ohio/OIBRSUOF.csv'
ohio_df = pd.read_csv(ohio_path, skiprows=1, encoding='latin-1')
ohio_df.drop(columns=["Unnamed: 16"], inplace=True)
ohio_df = reduce_memory_usage(ohio_df, verbose=True)
ohio_df["IncidentNumber"] = ohio_df["IncidentNumber"].str.replace("\t", "", regex=False)
print(ohio_df.shape)
ohio_df.head()

Memory usage before: 2.98 MB
Memory usage after: 2.98 MB
Reduced by 0.0%
(2993, 16)

,AgencyName,IncidentNumber,IncidentDate,InitialContactCircumstances,LocationType,SubjectResistanceTypes,SubjectArmed/BelievedToBeArmed,SubjectRaceEthnicity,SubjectGender,SubjectInjuries,SubjectImpairments,OfficerType,OfficerResponse/ForceTypes,OfficerRaceEthnicity,OfficerGender,OfficerInjuries
0,Akron,202400000028,1/1/2024,Unknown and is Unlikely to Ever be Known,Unknown And Is Unlikely To Ever Be Known,Failing to Comply to Verbal Commands | Pulling...,No,White,Male,NaN,NaN,Law Enforcement,Other Force Type Used | Restraining Hold | Oth...,White | White,Female | Male,Apparent Minor Injury | None
1,Ravenna,2240010006,1/1/2024,Other Circumstances,Government Office,Verbally Threatening Others,No,White,Male,NaN,Alcohol Impairment,Law Enforcement,Restraining Hold,White | White,Male | Male,NaN
2,Holland,24-000001-1,1/1/2024,Responding to Other Unlawful or Suspicious Act...,Single Family Home,Failing to Comply to Verbal Commands | Resisti...,No,Black or African American | Black or African A...,Male | Male,NaN,NaN,Law Enforcement,Balance Displacement | Electronic Control Devi...,White | White,Male | Male,NaN
3,Woodlawn,202400000001,1/1/2024,Traffic Stop,Single Family Home,Firearm Displayed at an Officer or Another,Yes,Black or African American,Female,NaN,NaN,Law Enforcement,Other Force Type Used,Black or African American | White,Male | Male,NaN
4,Cleveland,2024-000866,1/1/2024,Unknown and is Unlikely to Ever be Known,Unknown And Is Unlikely To Ever Be Known,Pulling Away | Punching/Kicking Officer or Ano...,Unknown and is Unlikely to Ever be Known,Unknown/Not Reported | Unknown/Not Reported | ...,Unknown/Not Reported | Female | Unknown/Not Re...,NaN,Alcohol Impairment,Law Enforcement,"Chemical Agent/Spray (Oleoresin Capsicum, Pepp...",Black or African American,Male,NaN

In [54]:
ohio_df[lambda x: x["SubjectResistanceTypes"].str.contains("|", regex=False)].shape

(2107, 16)

In [55]:
ohio_df[lambda x: x["SubjectResistanceTypes"].str.contains("|", regex=False)].head().T

,0,2,4,5,6
AgencyName,Akron,Holland,Cleveland,Greenhills,Ohio State Highway Patrol
IncidentNumber,202400000028,24-000001-1,2024-000866,202400000001,247700010377
IncidentDate,1/1/2024,1/1/2024,1/1/2024,1/1/2024,1/1/2024
InitialContactCircumstances,Unknown and is Unlikely to Ever be Known,Responding to Other Unlawful or Suspicious Act...,Unknown and is Unlikely to Ever be Known,Domestic Disturbance,Traffic Stop
LocationType,Unknown And Is Unlikely To Ever Be Known,Single Family Home,Unknown And Is Unlikely To Ever Be Known,Single Family Home,Street
SubjectResistanceTypes,Failing to Comply to Verbal Commands | Pulling...,Failing to Comply to Verbal Commands | Resisti...,Pulling Away | Punching/Kicking Officer or Ano...,Failing to Comply to Verbal Commands | Nonviol...,Deadweight | Failing to Comply to Verbal Commands
SubjectArmed/BelievedToBeArmed,No,No,Unknown and is Unlikely to Ever be Known,No,Yes
SubjectRaceEthnicity,White,Black or African American | Black or African A...,Unknown/Not Reported | Unknown/Not Reported | ...,White,Black or African American
SubjectGender,Male,Male | Male,Unknown/Not Reported | Female | Unknown/Not Re...,Male,Male
SubjectInjuries,NaN,NaN,NaN,NaN,Apparent Minor Injury
SubjectImpairments,NaN,NaN,Alcohol Impairment,NaN,Alcohol Impairment
OfficerType,Law Enforcement,Law Enforcement,Law Enforcement,Law Enforcement,Law Enforcement
OfficerResponse/ForceTypes,Other Force Type Used | Restraining Hold | Oth...,Balance Displacement | Electronic Control Devi...,"Chemical Agent/Spray (Oleoresin Capsicum, Pepp...",Balance Displacement | Restraining Hold,Take Down
OfficerRaceEthnicity,White | White,White | White,Black or African American,White | White,White
OfficerGender,Female | Male,Male | Male,Male,Male | Male,Male
OfficerInjuries,Apparent Minor Injury | None,NaN,NaN,NaN,NaN

In [56]:
ohio_df[lambda x: x["SubjectArmed/BelievedToBeArmed"].str.contains("|", regex=False)].shape

(14, 16)

In [57]:
ohio_df[lambda x: x["SubjectRaceEthnicity"].str.contains("|", regex=False)].shape

(217, 16)

In [58]:
ohio_df[lambda x: x["SubjectRaceEthnicity"].str.contains("|", regex=False)].head(2).T

,2,4
AgencyName,Holland,Cleveland
IncidentNumber,24-000001-1,2024-000866
IncidentDate,1/1/2024,1/1/2024
InitialContactCircumstances,Responding to Other Unlawful or Suspicious Act...,Unknown and is Unlikely to Ever be Known
LocationType,Single Family Home,Unknown And Is Unlikely To Ever Be Known
SubjectResistanceTypes,Failing to Comply to Verbal Commands | Resisti...,Pulling Away | Punching/Kicking Officer or Ano...
SubjectArmed/BelievedToBeArmed,No,Unknown and is Unlikely to Ever be Known
SubjectRaceEthnicity,Black or African American | Black or African A...,Unknown/Not Reported | Unknown/Not Reported | ...
SubjectGender,Male | Male,Unknown/Not Reported | Female | Unknown/Not Re...
SubjectInjuries,NaN,NaN
SubjectImpairments,NaN,Alcohol Impairment
OfficerType,Law Enforcement,Law Enforcement
OfficerResponse/ForceTypes,Balance Displacement | Electronic Control Devi...,"Chemical Agent/Spray (Oleoresin Capsicum, Pepp..."
OfficerRaceEthnicity,White | White,Black or African American
OfficerGender,Male | Male,Male
OfficerInjuries,NaN,NaN

In [59]:
ohio_df[lambda x: x["SubjectRaceEthnicity"].str.contains("|", regex=False)].loc[2]["SubjectResistanceTypes"]

'Failing to Comply to Verbal Commands | Resisting Being Handcuffed or Arrest'

In [60]:
ohio_df[lambda x: x["SubjectRaceEthnicity"].str.contains("|", regex=False)].loc[2]["OfficerResponse/ForceTypes"]

'Balance Displacement | Electronic Control Device (ECD) Discharged'

In [61]:
def expand_ohio_subjects(df):
    """
    For rows where multiple subjects are encoded with | as a delimiter,
    split into one row per subject.
    
    SubjectRaceEthnicity and SubjectGender are the anchors — the number
    of tokens they produce (split by |) defines how many rows a record expands to.
    
    For SubjectArmed/BelievedToBeArmed, SubjectInjuries, SubjectImpairments:
      - if the column has the same number of |-delimited tokens as the anchor, split them too
      - otherwise, carry the original value into every expanded row
    """
    anchor_cols = ["SubjectRaceEthnicity", "SubjectGender"]
    conditional_cols = [
        "SubjectArmed/BelievedToBeArmed",
        "SubjectInjuries",
        "SubjectImpairments",
    ]

    expanded_rows = []

    for idx, row in df.iterrows():
        # Split anchors by |
        race_val = row["SubjectRaceEthnicity"]
        gender_val = row["SubjectGender"]

        race_tokens = [t.strip() for t in str(race_val).split("|")] if pd.notna(race_val) else [race_val]
        gender_tokens = [t.strip() for t in str(gender_val).split("|")] if pd.notna(gender_val) else [gender_val]

        n = len(gender_tokens)

        # If gender token count mismatches race, broadcast gender to all rows
        if len(race_tokens) != n:
            race_tokens = [race_val] * n

        # Pre-split conditional columns
        cond_splits = {}
        for col in conditional_cols:
            val = row[col]
            if pd.notna(val):
                tokens = [t.strip() for t in str(val).split("|")]
                cond_splits[col] = tokens if len(tokens) == n else None
            else:
                cond_splits[col] = None

        for i in range(n):
            new_row = row.copy()
            new_row["SubjectRaceEthnicity"] = race_tokens[i]
            new_row["SubjectGender"] = gender_tokens[i]

            for col in conditional_cols:
                if cond_splits[col] is not None:
                    new_row[col] = cond_splits[col][i]
                # else: leave original broadcast value as-is

            expanded_rows.append(new_row)

    return pd.DataFrame(expanded_rows).reset_index(drop=True)


print("ohio_df shape before expansion:", ohio_df.shape)
ohio_df = expand_ohio_subjects(ohio_df)
print("ohio_df shape after expansion:", ohio_df.shape)

ohio_df shape before expansion: (2993, 16)
ohio_df shape after expansion: (3258, 16)

In [62]:
ohio_df[lambda x: x.IncidentNumber == "202400001349"]

,AgencyName,IncidentNumber,IncidentDate,InitialContactCircumstances,LocationType,SubjectResistanceTypes,SubjectArmed/BelievedToBeArmed,SubjectRaceEthnicity,SubjectGender,SubjectInjuries,SubjectImpairments,OfficerType,OfficerResponse/ForceTypes,OfficerRaceEthnicity,OfficerGender,OfficerInjuries
969,Blue Ash,202400001349,12/28/2024,Traffic Stop,Street,Deadweight | Failing to Comply to Verbal Commands,No,White | Hispanic or Latino | White | Hispanic ...,Male,None,NaN,Law Enforcement,Other Empty Hand Technique Used,Black or African American | White,Male | Male,NaN
970,Blue Ash,202400001349,12/28/2024,Traffic Stop,Street,Deadweight | Failing to Comply to Verbal Commands,No,White | Hispanic or Latino | White | Hispanic ...,Male,Unknown and is unlikely to ever be known,NaN,Law Enforcement,Other Empty Hand Technique Used,Black or African American | White,Male | Male,NaN

In [63]:
ohio_df.head()

,AgencyName,IncidentNumber,IncidentDate,InitialContactCircumstances,LocationType,SubjectResistanceTypes,SubjectArmed/BelievedToBeArmed,SubjectRaceEthnicity,SubjectGender,SubjectInjuries,SubjectImpairments,OfficerType,OfficerResponse/ForceTypes,OfficerRaceEthnicity,OfficerGender,OfficerInjuries
0,Akron,202400000028,1/1/2024,Unknown and is Unlikely to Ever be Known,Unknown And Is Unlikely To Ever Be Known,Failing to Comply to Verbal Commands | Pulling...,No,White,Male,NaN,NaN,Law Enforcement,Other Force Type Used | Restraining Hold | Oth...,White | White,Female | Male,Apparent Minor Injury | None
1,Ravenna,2240010006,1/1/2024,Other Circumstances,Government Office,Verbally Threatening Others,No,White,Male,NaN,Alcohol Impairment,Law Enforcement,Restraining Hold,White | White,Male | Male,NaN
2,Holland,24-000001-1,1/1/2024,Responding to Other Unlawful or Suspicious Act...,Single Family Home,Failing to Comply to Verbal Commands | Resisti...,No,Black or African American,Male,NaN,NaN,Law Enforcement,Balance Displacement | Electronic Control Devi...,White | White,Male | Male,NaN
3,Holland,24-000001-1,1/1/2024,Responding to Other Unlawful or Suspicious Act...,Single Family Home,Failing to Comply to Verbal Commands | Resisti...,No,Black or African American,Male,NaN,NaN,Law Enforcement,Balance Displacement | Electronic Control Devi...,White | White,Male | Male,NaN
4,Woodlawn,202400000001,1/1/2024,Traffic Stop,Single Family Home,Firearm Displayed at an Officer or Another,Yes,Black or African American,Female,NaN,NaN,Law Enforcement,Other Force Type Used,Black or African American | White,Male | Male,NaN

In [64]:
ohio_df.loc[1050]

AgencyName                                                                   Medina
IncidentNumber                                                          20-24004717
IncidentDate                                                              12/9/2024
InitialContactCircumstances                                    Domestic Disturbance
LocationType                                                      Multiple Dwelling
SubjectResistanceTypes            Attempt to Escape/Flee From Custody | Deadweig...
SubjectArmed/BelievedToBeArmed                                                   No
SubjectRaceEthnicity                                      Black or African American
SubjectGender                                                                  Male
SubjectInjuries                                                                 NaN
SubjectImpairments                                               Alcohol Impairment
OfficerType                                                         Law Enforcement
OfficerResponse/ForceTypes                         Balance Displacement | Take Down
OfficerRaceEthnicity                                                          White
OfficerGender                                                                  Male
OfficerInjuries                                                                 NaN
Name: 1050, dtype: str

In [65]:
ohio_df["OfficerResponse/ForceTypes"].str.split("|").explode().str.strip().value_counts()

OfficerResponse/ForceTypes
Restraining Hold                                                1421
Take Down                                                       1088
Other Force Type Used                                            919
Balance Displacement                                             628
Other Empty Hand Technique Used                                  625
Electronic Control Device (ECD) Discharged                       530
Pressure Point                                                   206
Chemical Agent/Spray (Oleoresin Capsicum, Pepper, etc.) Used     122
Canine                                                            39
Other Weapon (non-firearm) Used                                   34
Unknown and is Unlikely to Ever be Known                          23
Baton Used                                                        22
Pending Further Investigation                                     19
Handgun Fired                                                      9
Vehicle Used                                                       6
Bean Bags Used                                                     4
Rifle Fired                                                        3
Flashlight or Other Blunt Instrument Used                          3
Shotgun Fired                                                      2
Other Impact Projectile Used                                       2
Name: count, dtype: int64

## New York

In [66]:
ny_uof_path = './data/NewYork/UOF Case Level File_Nov2020-Dec2024.xlsx'
ny_uof_df = pd.read_excel(ny_uof_path)
ny_uof_df.head()

,Response ID\n(5/16/25 File),Agency Name,Incident Date,City/town/village (location Where Incident Occurred),County (location where incident occurred),Circumstance,Officer 1 - Use of Force Type,Officer 1 Age,Officer 1 Sex,Officer 1 Race,Officer 1 Ethnicity,Officer 2 - Use of Force Type,Officer 2 Age,Officer 2 Sex,Officer 2 Race,Officer 2 Ethnicity,Officer 3 - Use of Force Type,Officer 3 Age,Officer 3 Sex,Officer 3 Race,Officer 3 Ethnicity,Officer 4 - Use of Force Type,Officer 4 Age,Officer 4 Sex,Officer 4 Race,Officer 4 Ethnicity,Officer 5 - Use of Force Type,Officer 5 Age,Officer 5 Sex,Officer 5 Race,Officer 5 Ethnicity,Officer 6 - Use of Force Type,Officer 6 Age,Officer 6 Sex,Officer 6 Race,Officer 6 Ethnicity,Officer 7 - Use of Force Type,Officer 7 Age,Officer 7 Sex,Officer 7 Race,Officer 7 Ethnicity,Officer 8 - Use of Force Type,Officer 8 Age,Officer 8 Sex,Officer 8 Race,Officer 8 Ethnicity,Officer 9 - Use of Force Type,Officer 9 Age,Officer 9 Sex,Officer 9 Race,Officer 9 Ethnicity,Officer 10 - Use of Force Type,Officer 10 Age,Officer 10 Sex,Officer 10 Race,Officer 10 Ethnicity,Officer 11 - Use of Force Type,Officer 11 Age,Officer 11 Sex,Officer 11 Race,Officer 11 Ethnicity,Officer 12 - Use of Force Type,Officer 12 Age,Officer 12 Sex,Officer 12 Race,Officer 12 Ethnicity,Officer 13 - Use of Force Type,Officer 13 Age,Officer 13 Sex,Officer 13 Race,Officer 13 Ethnicity,Officer 14 - Use of Force Type,Officer 14 Age,Officer 14 Sex,Officer 14 Race,Officer 14 Ethnicity,Officer 15 - Use of Force Type,Officer 15 Age,Officer 15 Sex,Officer 15 Race,Officer 15 Ethnicity,Officer 16 - Use of Force Type,Officer 16 Age,Officer 16 Sex,Officer 16 Race,Officer 16 Ethnicity,Subject 1 Age,Subject 1 Sex,Subject 1 Race,Subject 1 Ethnicity,Subject 2 Age,Subject 2 Sex,Subject 2 Race,Subject 2 Ethnicity,Subject 3 Age,Subject 3 Sex,Subject 3 Race,Subject 3 Ethnicity,Subject 4 Age,Subject 4 Sex,Subject 4 Race,Subject 4 Ethnicity,Subject 5 Age,Subject 5 Sex,Subject 5 Race,Subject 5 Ethnicity,Subject 6 Age,Subject 6 Sex,Subject 6 Race,Subject 6 Ethnicity,Subject 7 Age,Subject 7 Sex,Subject 7 Race,Subject 7 Ethnicity,Subject 8 Age,Subject 8 Sex,Subject 8 Race,Subject 8 Ethnicity,Subject 9 Age,Subject 9 Sex,Subject 9 Race,Subject 9 Ethnicity,Subject 10 Age,Subject 10 Sex,Subject 10 Race,Subject 10 Ethnicity,Subject 11 Age,Subject 11 Sex,Subject 11 Race,Subject 11 Ethnicity,Subject 12 Age,Subject 12 Sex,Subject 12 Race,Subject 12 Ethnicity,Subject 13 Age,Subject 13 Sex,Subject 13 Race,Subject 13 Ethnicity,Subject 14 Age,Subject 14 Sex,Subject 14 Race,Subject 14 Ethnicity,Subject 15 Age,Subject 15 Sex,Subject 15 Race,Subject 15 Ethnicity,Subject 16 Age,Subject 16 Sex,Subject 16 Race,Subject 16 Ethnicity,Subject 17 Age,Subject 17 Sex,Subject 17 Race,Subject 17 Ethnicity,Subject 18 Age,Subject 18 Sex,Subject 18 Race,Subject 18 Ethnicity,Subject 19 Age,Subject 19 Sex,Subject 19 Race,Subject 19 Ethnicity,Subject 20 Age,Subject 20 Sex,Subject 20 Race,Subject 20 Ethnicity,Subject 21 Age,Subject 21 Sex,Subject 21 Race,Subject 21 Ethnicity,Subject 22 Age,Subject 22 Sex,Subject 22 Race,Subject 22 Ethnicity,Subject 23 Age,Subject 23 Sex,Subject 23 Race,Subject 23 Ethnicity,Subject 24 Age,Subject 24 Sex,Subject 24 Race,Subject 24 Ethnicity,Subject 25 Age,Subject 25 Sex,Subject 25 Race,Subject 25 Ethnicity
0,1,Akron Vg PD,2020-12-22,Akron,Erie,Response to unlawful or suspicious activity,Pointed Firearm,27.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Albany City PD,2020-11-10,Albany,Albany,Other,Used/Deployed Chemical Agent,37.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Male,Black,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Albany City PD,2020-11-20,Albany,Albany,Other,Pointed Firearm,45.0000,Male,White,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0000,Male,Black,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Albany City PD,2020-12-08,Albany,Albany,Executing Arrest,Pointed Electronic Control Weapon,50.0000,Male,White,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0000,Male,Black,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Albany City PD,2021-01-11,Albany,Albany,Executing Arrest,Pointed Firearm,32.0000,Male,White,Non-Hispanic,Pointed Firearm,25.0000,Male,White,Unknown,Pointed Electronic Control Weapon,34.0000,Male,Asian,Unknown,Pointed Electronic Control Weapon,36.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0000,Male,Black,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
ny_uof_df.shape

(34837, 186)

In [68]:
(
    ny_uof_df
        [lambda x: x["Incident Date"].between(datetime(2024,1,1), datetime(2024,12,31), inclusive="both")]
        .sort_values(by="Incident Date")
)

,Response ID\n(5/16/25 File),Agency Name,Incident Date,City/town/village (location Where Incident Occurred),County (location where incident occurred),Circumstance,Officer 1 - Use of Force Type,Officer 1 Age,Officer 1 Sex,Officer 1 Race,Officer 1 Ethnicity,Officer 2 - Use of Force Type,Officer 2 Age,Officer 2 Sex,Officer 2 Race,Officer 2 Ethnicity,Officer 3 - Use of Force Type,Officer 3 Age,Officer 3 Sex,Officer 3 Race,Officer 3 Ethnicity,Officer 4 - Use of Force Type,Officer 4 Age,Officer 4 Sex,Officer 4 Race,Officer 4 Ethnicity,Officer 5 - Use of Force Type,Officer 5 Age,Officer 5 Sex,Officer 5 Race,Officer 5 Ethnicity,Officer 6 - Use of Force Type,Officer 6 Age,Officer 6 Sex,Officer 6 Race,Officer 6 Ethnicity,Officer 7 - Use of Force Type,Officer 7 Age,Officer 7 Sex,Officer 7 Race,Officer 7 Ethnicity,Officer 8 - Use of Force Type,Officer 8 Age,Officer 8 Sex,Officer 8 Race,Officer 8 Ethnicity,Officer 9 - Use of Force Type,Officer 9 Age,Officer 9 Sex,Officer 9 Race,Officer 9 Ethnicity,Officer 10 - Use of Force Type,Officer 10 Age,Officer 10 Sex,Officer 10 Race,Officer 10 Ethnicity,Officer 11 - Use of Force Type,Officer 11 Age,Officer 11 Sex,Officer 11 Race,Officer 11 Ethnicity,Officer 12 - Use of Force Type,Officer 12 Age,Officer 12 Sex,Officer 12 Race,Officer 12 Ethnicity,Officer 13 - Use of Force Type,Officer 13 Age,Officer 13 Sex,Officer 13 Race,Officer 13 Ethnicity,Officer 14 - Use of Force Type,Officer 14 Age,Officer 14 Sex,Officer 14 Race,Officer 14 Ethnicity,Officer 15 - Use of Force Type,Officer 15 Age,Officer 15 Sex,Officer 15 Race,Officer 15 Ethnicity,Officer 16 - Use of Force Type,Officer 16 Age,Officer 16 Sex,Officer 16 Race,Officer 16 Ethnicity,Subject 1 Age,Subject 1 Sex,Subject 1 Race,Subject 1 Ethnicity,Subject 2 Age,Subject 2 Sex,Subject 2 Race,Subject 2 Ethnicity,Subject 3 Age,Subject 3 Sex,Subject 3 Race,Subject 3 Ethnicity,Subject 4 Age,Subject 4 Sex,Subject 4 Race,Subject 4 Ethnicity,Subject 5 Age,Subject 5 Sex,Subject 5 Race,Subject 5 Ethnicity,Subject 6 Age,Subject 6 Sex,Subject 6 Race,Subject 6 Ethnicity,Subject 7 Age,Subject 7 Sex,Subject 7 Race,Subject 7 Ethnicity,Subject 8 Age,Subject 8 Sex,Subject 8 Race,Subject 8 Ethnicity,Subject 9 Age,Subject 9 Sex,Subject 9 Race,Subject 9 Ethnicity,Subject 10 Age,Subject 10 Sex,Subject 10 Race,Subject 10 Ethnicity,Subject 11 Age,Subject 11 Sex,Subject 11 Race,Subject 11 Ethnicity,Subject 12 Age,Subject 12 Sex,Subject 12 Race,Subject 12 Ethnicity,Subject 13 Age,Subject 13 Sex,Subject 13 Race,Subject 13 Ethnicity,Subject 14 Age,Subject 14 Sex,Subject 14 Race,Subject 14 Ethnicity,Subject 15 Age,Subject 15 Sex,Subject 15 Race,Subject 15 Ethnicity,Subject 16 Age,Subject 16 Sex,Subject 16 Race,Subject 16 Ethnicity,Subject 17 Age,Subject 17 Sex,Subject 17 Race,Subject 17 Ethnicity,Subject 18 Age,Subject 18 Sex,Subject 18 Race,Subject 18 Ethnicity,Subject 19 Age,Subject 19 Sex,Subject 19 Race,Subject 19 Ethnicity,Subject 20 Age,Subject 20 Sex,Subject 20 Race,Subject 20 Ethnicity,Subject 21 Age,Subject 21 Sex,Subject 21 Race,Subject 21 Ethnicity,Subject 22 Age,Subject 22 Sex,Subject 22 Race,Subject 22 Ethnicity,Subject 23 Age,Subject 23 Sex,Subject 23 Race,Subject 23 Ethnicity,Subject 24 Age,Subject 24 Sex,Subject 24 Race,Subject 24 Ethnicity,Subject 25 Age,Subject 25 Sex,Subject 25 Race,Subject 25 Ethnicity
26977,26978,Syracuse City PD,2024-01-01,Syracuse,Onondaga,Response to unlawful or suspicious activity,Pointed Electronic Control Weapon,26.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0000,Male,Black,Unknown,NaN,Male,Black,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9542,9543,Manlius Town PD,2024-01-01,Manlius,Onondaga,Traffic Stop,Pointed Firearm,29.0000,Male,White,Non-Hispanic,Pointed Firearm,35.0000,Male,Black,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4449,4450,Corning City PD,2024-01-01,Corning,Steuben,Executing Arrest,Pointed Firearm,40.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.0000,Male,Black,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25814,25815,Suffolk County PD,2024-01-01,West Babylon,Suffolk,Response to unlawful or suspicious activity,Pointed Firearm,55.0000,Male,White,Non-Hispanic,Pointed Firearm,30.0000,Male,Black,Non-Hispanic,Pointed Firearm,28.0000,Male,White,Non-Hispanic,Pointed Firearm,24.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0000,Male,White,Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14640,14641,New York State Police,2024-01-01,New York,New York,Routine patrol other than traffic stop,"Pointed Firearm,Pointed Impact Weapon",39.0000,Male,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10211,10212,Monroe County Sheriff,2024-12-31,Rochester,Monroe,JAIL - Responding to a Disturbance,Used/Deployed Chemical Agent,28.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.0000,Male,White,Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1110,1111,Amherst Town PD,2024-12-31,Amherst,Erie,"Medical, mental health, or welfare assistance",Pointed Firearm,40.0000,Male,White,Non-Hispanic,Pointed Electronic Control Weapon,27.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0000,Male,Black,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26074,26075,Suffolk County PD,2024-12-31,Selden,Suffolk,"Medical, mental health, or welfare assistance",Pointed Firearm,57.0000,Male,White,Non-Hispanic,Pointed Firearm,34.0000,Male,White,Non-Hispanic,Pointed Firearm,34.0000,Male,White,Non-Hispanic,Used/Deployed Electronic Control Weapon,33.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3072,3073,Buffalo City PD,2024-12-31,Buffalo,Erie,Response to unlawful or suspicious activity,Displayed Chemical Agent,42.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.0000,Male,White,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18401,18402,New York City Police Department,2024-12-31,BRONX,Bronx,Response to unlawful or suspicious activity,Used/Deployed Electronic Control Weapon,23.0000,Male,Unknown,Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.0000,Male,Black,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
ny_uof_df[~ny_uof_df["Subject 25 Race"].isna()]

,Response ID\n(5/16/25 File),Agency Name,Incident Date,City/town/village (location Where Incident Occurred),County (location where incident occurred),Circumstance,Officer 1 - Use of Force Type,Officer 1 Age,Officer 1 Sex,Officer 1 Race,Officer 1 Ethnicity,Officer 2 - Use of Force Type,Officer 2 Age,Officer 2 Sex,Officer 2 Race,Officer 2 Ethnicity,Officer 3 - Use of Force Type,Officer 3 Age,Officer 3 Sex,Officer 3 Race,Officer 3 Ethnicity,Officer 4 - Use of Force Type,Officer 4 Age,Officer 4 Sex,Officer 4 Race,Officer 4 Ethnicity,Officer 5 - Use of Force Type,Officer 5 Age,Officer 5 Sex,Officer 5 Race,Officer 5 Ethnicity,Officer 6 - Use of Force Type,Officer 6 Age,Officer 6 Sex,Officer 6 Race,Officer 6 Ethnicity,Officer 7 - Use of Force Type,Officer 7 Age,Officer 7 Sex,Officer 7 Race,Officer 7 Ethnicity,Officer 8 - Use of Force Type,Officer 8 Age,Officer 8 Sex,Officer 8 Race,Officer 8 Ethnicity,Officer 9 - Use of Force Type,Officer 9 Age,Officer 9 Sex,Officer 9 Race,Officer 9 Ethnicity,Officer 10 - Use of Force Type,Officer 10 Age,Officer 10 Sex,Officer 10 Race,Officer 10 Ethnicity,Officer 11 - Use of Force Type,Officer 11 Age,Officer 11 Sex,Officer 11 Race,Officer 11 Ethnicity,Officer 12 - Use of Force Type,Officer 12 Age,Officer 12 Sex,Officer 12 Race,Officer 12 Ethnicity,Officer 13 - Use of Force Type,Officer 13 Age,Officer 13 Sex,Officer 13 Race,Officer 13 Ethnicity,Officer 14 - Use of Force Type,Officer 14 Age,Officer 14 Sex,Officer 14 Race,Officer 14 Ethnicity,Officer 15 - Use of Force Type,Officer 15 Age,Officer 15 Sex,Officer 15 Race,Officer 15 Ethnicity,Officer 16 - Use of Force Type,Officer 16 Age,Officer 16 Sex,Officer 16 Race,Officer 16 Ethnicity,Subject 1 Age,Subject 1 Sex,Subject 1 Race,Subject 1 Ethnicity,Subject 2 Age,Subject 2 Sex,Subject 2 Race,Subject 2 Ethnicity,Subject 3 Age,Subject 3 Sex,Subject 3 Race,Subject 3 Ethnicity,Subject 4 Age,Subject 4 Sex,Subject 4 Race,Subject 4 Ethnicity,Subject 5 Age,Subject 5 Sex,Subject 5 Race,Subject 5 Ethnicity,Subject 6 Age,Subject 6 Sex,Subject 6 Race,Subject 6 Ethnicity,Subject 7 Age,Subject 7 Sex,Subject 7 Race,Subject 7 Ethnicity,Subject 8 Age,Subject 8 Sex,Subject 8 Race,Subject 8 Ethnicity,Subject 9 Age,Subject 9 Sex,Subject 9 Race,Subject 9 Ethnicity,Subject 10 Age,Subject 10 Sex,Subject 10 Race,Subject 10 Ethnicity,Subject 11 Age,Subject 11 Sex,Subject 11 Race,Subject 11 Ethnicity,Subject 12 Age,Subject 12 Sex,Subject 12 Race,Subject 12 Ethnicity,Subject 13 Age,Subject 13 Sex,Subject 13 Race,Subject 13 Ethnicity,Subject 14 Age,Subject 14 Sex,Subject 14 Race,Subject 14 Ethnicity,Subject 15 Age,Subject 15 Sex,Subject 15 Race,Subject 15 Ethnicity,Subject 16 Age,Subject 16 Sex,Subject 16 Race,Subject 16 Ethnicity,Subject 17 Age,Subject 17 Sex,Subject 17 Race,Subject 17 Ethnicity,Subject 18 Age,Subject 18 Sex,Subject 18 Race,Subject 18 Ethnicity,Subject 19 Age,Subject 19 Sex,Subject 19 Race,Subject 19 Ethnicity,Subject 20 Age,Subject 20 Sex,Subject 20 Race,Subject 20 Ethnicity,Subject 21 Age,Subject 21 Sex,Subject 21 Race,Subject 21 Ethnicity,Subject 22 Age,Subject 22 Sex,Subject 22 Race,Subject 22 Ethnicity,Subject 23 Age,Subject 23 Sex,Subject 23 Race,Subject 23 Ethnicity,Subject 24 Age,Subject 24 Sex,Subject 24 Race,Subject 24 Ethnicity,Subject 25 Age,Subject 25 Sex,Subject 25 Race,Subject 25 Ethnicity
3025,3026,Buffalo City PD,2024-10-14,Buffalo,Erie,Service of a warrant,Pointed Firearm,55.0000,Male,White,Non-Hispanic,Pointed Firearm,40.0000,Male,White,Hispanic,Pointed Firearm,45.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0000,Female,Black,Non-Hispanic,56.0000,Female,Black,Non-Hispanic,32.0000,Female,Black,Non-Hispanic,35.0000,Female,Black,Unknown,26.0000,Male,Black,Non-Hispanic,35.0000,Female,Black,Unknown,36.0000,Female,White,Unknown,24.0000,Male,Black,Unknown,31.0000,Female,White,Non-Hispanic,40.0000,Female,White,Non-Hispanic,22.0000,Male,Black,Non-Hispanic,28.0000,Male,Black,Non-Hispanic,28.0000,Male,Black,Non-Hispanic,22.0000,Male,Black,Non-Hispanic,35.0000,Male,Black,Non-Hispanic,39.0000,Male,Black,Non-Hispanic,34.0000,Male,White,Non-Hispanic,21.0000,Female,Black,Non-Hispanic,40.0000,Female,White,Non-Hispanic,31.0000,Female,White,Non-Hispanic,44.0000,Male,White,Non-Hispanic,39.0000,Female,White,Non-Hispanic,42.0000,Female,White,Non-Hispanic,31.0000,Female,Black,Non-Hispanic,56.0000,Female,Black,Non-Hispanic

In [70]:
ny_uof_df = ny_uof_df.reset_index(drop=True).rename_axis("incident_id").reset_index()
# Identify non-subject columns
id_cols = [
    col for col in ny_uof_df.columns
    if not re.match(r"Subject \d+ (Race|Ethnicity|Age|Sex)$", col)
]

# Rename subject columns to the format wide_to_long expects: "race1", "race2", etc.
rename_map = {}
for col in ny_uof_df.columns:
    m = re.match(r"Subject (\d+) (Race|Ethnicity|Age|Sex)$", col)
    if m:
        num, attr = m.groups()
        rename_map[col] = f"{attr.lower()}{num}"

ny_uof_long = (
    ny_uof_df
    .rename(columns=rename_map)
    .pipe(pd.wide_to_long,
          stubnames=["race", "ethnicity", "age", "sex"],
          i=id_cols,
          j="subject_number")
    .reset_index()
    .rename(columns={"race": "subject_race", "ethnicity": "subject_ethnicity",
                     "age": "subject_age", "sex": "subject_sex"})
    .loc[lambda df: ~(
        df[["subject_race", "subject_ethnicity", "subject_age", "subject_sex"]]
        .isin([""])
        .all(axis=1)
        & df[["subject_race", "subject_ethnicity", "subject_age", "subject_sex"]]
        .isna()
        .all(axis=1)
    )]
    .reset_index(drop=True)
)
subject_cols = ["subject_race", "subject_ethnicity", "subject_age", "subject_sex"]
ny_uof_long = ny_uof_long.dropna(subset=subject_cols, how="all")

In [71]:
ny_uof_long

,incident_id,Response ID\n(5/16/25 File),Agency Name,Incident Date,City/town/village (location Where Incident Occurred),County (location where incident occurred),Circumstance,Officer 1 - Use of Force Type,Officer 1 Age,Officer 1 Sex,Officer 1 Race,Officer 1 Ethnicity,Officer 2 - Use of Force Type,Officer 2 Age,Officer 2 Sex,Officer 2 Race,Officer 2 Ethnicity,Officer 3 - Use of Force Type,Officer 3 Age,Officer 3 Sex,Officer 3 Race,Officer 3 Ethnicity,Officer 4 - Use of Force Type,Officer 4 Age,Officer 4 Sex,Officer 4 Race,Officer 4 Ethnicity,Officer 5 - Use of Force Type,Officer 5 Age,Officer 5 Sex,Officer 5 Race,Officer 5 Ethnicity,Officer 6 - Use of Force Type,Officer 6 Age,Officer 6 Sex,Officer 6 Race,Officer 6 Ethnicity,Officer 7 - Use of Force Type,Officer 7 Age,Officer 7 Sex,Officer 7 Race,Officer 7 Ethnicity,Officer 8 - Use of Force Type,Officer 8 Age,Officer 8 Sex,Officer 8 Race,Officer 8 Ethnicity,Officer 9 - Use of Force Type,Officer 9 Age,Officer 9 Sex,Officer 9 Race,Officer 9 Ethnicity,Officer 10 - Use of Force Type,Officer 10 Age,Officer 10 Sex,Officer 10 Race,Officer 10 Ethnicity,Officer 11 - Use of Force Type,Officer 11 Age,Officer 11 Sex,Officer 11 Race,Officer 11 Ethnicity,Officer 12 - Use of Force Type,Officer 12 Age,Officer 12 Sex,Officer 12 Race,Officer 12 Ethnicity,Officer 13 - Use of Force Type,Officer 13 Age,Officer 13 Sex,Officer 13 Race,Officer 13 Ethnicity,Officer 14 - Use of Force Type,Officer 14 Age,Officer 14 Sex,Officer 14 Race,Officer 14 Ethnicity,Officer 15 - Use of Force Type,Officer 15 Age,Officer 15 Sex,Officer 15 Race,Officer 15 Ethnicity,Officer 16 - Use of Force Type,Officer 16 Age,Officer 16 Sex,Officer 16 Race,Officer 16 Ethnicity,subject_number,subject_race,subject_ethnicity,subject_age,subject_sex
0,0,1,Akron Vg PD,2020-12-22,Akron,Erie,Response to unlawful or suspicious activity,Pointed Firearm,27.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,White,Non-Hispanic,49.0000,Male
25,1,2,Albany City PD,2020-11-10,Albany,Albany,Other,Used/Deployed Chemical Agent,37.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,NaN,Male
50,2,3,Albany City PD,2020-11-20,Albany,Albany,Other,Pointed Firearm,45.0000,Male,White,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,49.0000,Male
75,3,4,Albany City PD,2020-12-08,Albany,Albany,Executing Arrest,Pointed Electronic Control Weapon,50.0000,Male,White,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,25.0000,Male
100,4,5,Albany City PD,2021-01-11,Albany,Albany,Executing Arrest,Pointed Firearm,32.0000,Male,White,Non-Hispanic,Pointed Firearm,25.0000,Male,White,Unknown,Pointed Electronic Control Weapon,34.0000,Male,Asian,Unknown,Pointed Electronic Control Weapon,36.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,38.0000,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870825,34833,34834,New York City Police Department,2023-12-31,Brooklyn,Kings,"Medical, mental health, or welfare assistance",Used/Deployed Electronic Control Weapon,25.0000,Male,Asian,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,White,Non-Hispanic,33.0000,Male
870850,34834,34835,New York City Police Department,2023-12-31,Brooklyn,Kings,Response to unlawful or suspicious activity,Used/Deployed Electronic Control Weapon,32.0000,Male,Black,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Non-Hispanic,19.0000,Male
870851,34834,34835,New York City Police Department,2023-12-31,Brooklyn,Kings,Response to unlawful or suspicious activity,Used/Deployed Electronic Control Weapon,32.0000,Male,Black,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,White,Hispanic,19.0000,Female
870875,34835,34836,New York City Police Department,2023-12-31,New York,New York,Response to unlawful or suspicious activity,Used/Deployed Electronic Control Weapon,35.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,White,Hispanic,43.0000,Male
870900,34836,34837,New York City Police Department,2023-12-31,Queens,Queens,Other,Used/Deployed Electronic Control Weapon,23.0000,Male,Asian,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Hispanic,25.0000,Male

In [72]:
ny_uof_long = reduce_memory_usage(ny_uof_long, verbose=True)

Memory usage before: 116.60 MB
Memory usage after: 113.21 MB
Reduced by 2.9%

In [73]:
ny_incidents_path = './data/NewYork/NYPD_Use_of_Force_Incidents_20260211.csv'
ny_incidents_df = pd.read_csv(ny_incidents_path)

ny_subjects_path = './data/NewYork/NYPD_Use_of_Force__Subjects_20260211.csv'
ny_subjects_df = pd.read_csv(ny_subjects_path)

print(ny_incidents_df.shape)
display(ny_incidents_df.head())
print(ny_subjects_df.shape)
ny_subjects_df.head()

(56994, 7)

,TRI Incident Number,ForceType,Occurrence Date,Incident Pct,Patrol Borough,YearMonthShort,BasisForEncounter
0,2024032962162,Physical Force,08/31/2024,13,PBMS,2024 Aug,CRIME/VIOLATION IN PROGRESS
1,2024033962356,Physical Force,08/31/2024,14,PBMS,2024 Aug,CRIME/VIOLATION IN PROGRESS
2,2024090962120,Physical Force,08/31/2024,71,PBBS,2024 Aug,CRIME/VIOLATION IN PROGRESS
3,2024096962122,Physical Force,08/31/2024,77,PBBN,2024 Aug,CRIME/VIOLATION IN PROGRESS
4,2024081962083,Physical Force,08/31/2024,62,PBBS,2024 Aug,CRIME/VIOLATION IN PROGRESS

(58585, 8)

,TRI Incident Number,Subject Injury Level,Subject Injured,Age,Subject Race,Subject Gender,Force Against MOS,Subject Used Force
0,2020020962067,No Injury,N,NaN,BLACK,MALE,Physical Force,Y
1,2020020962143,No Injury,N,NaN,BLACK,MALE,Physical Force,Y
2,2020024962080,No Injury,N,NaN,BLACK,MALE,Physical Force,Y
3,2020025962038,No Injury,N,NaN,BLACK,MALE,Physical Force,Y
4,2020025962049,No Injury,N,NaN,BLACK,MALE,Physical Force,Y

In [74]:
ny_df = pd.merge(left=ny_incidents_df, right=ny_subjects_df, on="TRI Incident Number")
ny_df = reduce_memory_usage(ny_df, verbose=True)

print(ny_df.shape)
ny_df.head()

Memory usage before: 36.71 MB
Memory usage after: 36.15 MB
Reduced by 1.5%
(58585, 14)

,TRI Incident Number,ForceType,Occurrence Date,Incident Pct,Patrol Borough,YearMonthShort,BasisForEncounter,Subject Injury Level,Subject Injured,Age,Subject Race,Subject Gender,Force Against MOS,Subject Used Force
0,2024032962162,Physical Force,08/31/2024,13,PBMS,2024 Aug,CRIME/VIOLATION IN PROGRESS,No Injury,N,17.0000,BLACK,MALE,Physical Force,Y
1,2024033962356,Physical Force,08/31/2024,14,PBMS,2024 Aug,CRIME/VIOLATION IN PROGRESS,No Injury,N,30.0000,BLACK,MALE,Physical Force,Y
2,2024090962120,Physical Force,08/31/2024,71,PBBS,2024 Aug,CRIME/VIOLATION IN PROGRESS,No Injury,N,19.0000,OTHER,MALE,Physical Force,Y
3,2024096962122,Physical Force,08/31/2024,77,PBBN,2024 Aug,CRIME/VIOLATION IN PROGRESS,No Injury,N,38.0000,BLACK,MALE,Physical Force,Y
4,2024081962083,Physical Force,08/31/2024,62,PBBS,2024 Aug,CRIME/VIOLATION IN PROGRESS,Physical Injury,Y,17.0000,HISPANIC,MALE,Physical Force,Y

In [75]:
ny_df["ForceType"].value_counts()

ForceType
Physical Force              48068
Electrical Weapon            8898
OC Spray                      950
Impact Weapon                 438
Firearm                       213
Restraining Mesh Blanket       13
Police Canine                   5
Name: count, dtype: int64

In [76]:
ny_df["Occurrence Date"].dtype

In [77]:
ny_df[lambda x: (x.ForceType == "Firearm") & (x["Occurrence Date"].str.contains("2024"))].shape

(34, 14)

In [78]:
ny_df[lambda x: (x.ForceType == "Restraining Mesh Blanket") & (x["Occurrence Date"].str.contains("2024"))].shape

(0, 14)

## California

In [79]:
cali_dir = './data/California/Final files'
cali_file_names = [item.name for item in Path(cali_dir).iterdir() if item.is_file()]
cali_file_paths = [cali_dir + "/" + name for name in cali_file_names if '.xlsx' in name]
print(len(cali_file_paths))
print(cali_file_paths[0])

65
./data/California/Final files/RIPA Stop Data_San Francisco 2024_final.xlsx

In [80]:
cali_path = cali_dir + "/cali_data.csv"
if not os.path.exists(cali_path):
    dfs = []

    for path, name in tqdm(zip(cali_file_paths, cali_file_names)):
        match = re.search(r'_(.*?)2024', name)
        county = match.group(1) if match else ""
        
        # 1. Read the file
        # 2. .copy() forces immediate de-fragmentation
        # 3. .assign() adds the column to the clean copy
        temp_df = pd.read_excel(path).copy()
        temp_df = temp_df.assign(county_name=county)
        
        dfs.append(temp_df)

    # Final concatenation
    cali_df = pd.concat(dfs, ignore_index=True)
    race_cols_to_drop = [c for c in cali_df.columns if c.startswith('RAE_') and c != 'RAE_FULL']
    gender_cols_to_drop = [c for c in cali_df.columns if c.startswith('G_') and c != 'G_FULL']
    sex_cols_to_drop = ['SOR_LGB']
    pd_cols_to_drop = [c for c in cali_df.columns if c.startswith('PD_') and c != 'PD_FULL']

    cali_df = cali_df.drop(columns=race_cols_to_drop + gender_cols_to_drop + sex_cols_to_drop)

    cali_df = reduce_memory_usage(cali_df, verbose=True)
    cali_df.to_csv(cali_path, index=False)
    del dfs
    gc.collect()

In [81]:
cali_df = pd.read_csv(cali_path)
print(cali_df.shape)
cali_df.head()

/var/folders/8r/qgk4_l1j20gfq28wvs_pxh2r0000gn/T/ipykernel_4510/3596666226.py:1: DtypeWarning: Columns (0: SCHOOL_CODE, 1: SCHOOL_NAME, 2: RFS_PC_CODE, 3: ROS_CITATION_CDS, 4: ROS_IN_FIELD_CITE_RELEASE_CDS, 5: ROS_CUSTODIAL_WOUT_WARRANT_CDS, 6: ROS_VERBAL_WARNING_CDS, 7: ROS_WRITTEN_WARNING_CDS) have mixed types. Specify dtype option on import or set low_memory=False.
  cali_df = pd.read_csv(cali_path)

(5065428, 179)

,DOJ_RECORD_ID,PERSON_NUMBER,AGENCY_ORI,AGENCY_NAME,NON_REPORTING_AGENCY,TIME_OF_STOP,DATE_OF_STOP,STOP_DURATION,LOC_CLOSEST_CITY,SCHOOL_CODE,SCHOOL_NAME,STOP_STUDENT,K12_SCHOOL_GROUNDS,RAE_FULL,G_FULL,SOR_STRAIGHT,AGE,AGE_GROUP,LIMITED_ENGLISH_FLUENCY,PD_FULL,PERSON_UNHOUSED,PASSENGER_IN_VEHICLE,INSIDE_RESIDENCE,WELFARE_WELLNESS_CHECK,TOS_VEHICULAR,TOS_BICYCLE,TOS_PEDESTRIAN,CALL_FOR_SERVICE,REASON_FOR_STOP,RFS_TRAFFIC_VIOLATION_TYPE,RFS_TRAFFIC_VIOLATION_CODE,RFS_RS_OFF_WITNESS,RFS_RS_MATCH_SUSPECT,RFS_RS_WITNESS_ID,RFS_RS_CARRY_SUS_OBJECT,RFS_RS_ACTIONS_INDICATIVE,RFS_RS_SUSPECT_LOOK,RFS_RS_DRUG_TRANS,RFS_RS_VIOLENT_CRIME,RFS_RS_REASON_SUSP,RFS_RS_MATCH_VEHICLE,RFS_RS_CODE,RFS_EC_DISCIPLINE_CODE,RFS_EC_DISCIPLINE,RFS_PC_OFF_WITNESS,RFS_PC_MATCH_SUSPECT,RFS_PC_WITNESS_ID,RFS_PC_CARRY_SUS_OBJECT,RFS_PC_ACTIONS_INDICATIVE,RFS_PC_SUSPECT_LOOK,RFS_PC_DRUG_TRANS,RFS_PC_VIOLENT_CRIME,RFS_PC_REASON_SUSP,RFS_PC_MATCH_VEHICLE,RFS_PC_CODE,RFS_RG_TRAFFIC_MOVING,RFS_RG_TRAFFIC_EQUIPMENT,RFS_RG_TRAFFIC_NON_MOVING,RFS_RG_OFF_WITNESS,RFS_RG_MATCH_SUSPECT,RFS_RG_MATCH_VEHICLE,RFS_RG_WITNESS_ID,RFS_RG_CARRY_SUS_OBJECT,RFS_RG_ACTIONS_INDICATIVE,RFS_RG_SUSPECT_LOOK,RFS_RG_DRUG_TRANS,RFS_RG_VIOLENT_CRIME,RFS_RG_REASON_SUSP,RFS_RG_PROBABLE_CAUSE,RFS_RG_WELFARE_AND_INST,RFS_RG_KNOWN_PAROLE,RFS_RG_OUTSTANDING_WARRANT,RFS_RG_TRUANT,RFS_RG_CONSENSUAL_SEARCH,RFS_RG_DISCIPLINE,RFS_RG_SCHOOL_POLICY,RFS_RG_NOT_COMMUNICATED,NFA_WRITTEN_STATEMENT,NFA_ASKED_SEARCH_PER,NFA_ASKED_SEARCH_PROP,NFA_ASKED_ID_PASSENGER,NFA_ASKED_PAROLE,NFA_CURB_DETENT,NFA_SOBRIETY_TEST,NFA_PATCAR_DETENT,NFA_CANINE_SEARCH,NFA_PHOTO,NFA_REMOVED_VEHICLE_ORDER,NFA_PROP_SEIZE,NFA_RAN_NAME_PASSENGER,NFA_SEARCH_PERSON,NFA_SEARCH_PROPERTY,NFA_TERRY_FRISK,NFA_VEHICLE_IMPOUND,NFA_NONE,NFA_SEARCH_PERS_CONSENT,NFA_SEARCH_PROP_CONSENT,OFA_HANDCUFFED,OFA_BATON_DRAWN,OFA_BATON_USED,OFA_CHEM_SPRAY,OFA_ELECT_DEVICE_POINT,OFA_ELECT_DEVICE_STUN,OFA_ELECT_DEVICE_DART,OFA_FIREARM_UNHOLSTERED,OFA_FIREARM_POINT,OFA_FIREARM_DISCHARGE,OFA_IMPACT_PROJECTILE_POINT,OFA_IMPACT_PROJECTILE_DISCHARGE,OFA_CANINE_COMPLIANCE,OFA_CANINE_BITE,OFA_REMOVED_VEHICLE_PHYCONTACT,OFA_PHYSICAL_COMPLIANCE,OFA_USE_VEHICLE,OFA_NONE,BFS_OFFICER_SAFETY,BFS_SEARCH_WARRANT,BFS_PAROLE,BFS_SUSPECT_WEAPON,BFS_VISIBLE_CONTRABAND,BFS_ODOR_CONTRABAND,BFS_CANINE_DETECT,BFS_EVIDENCE,BFS_INCIDENT,BFS_EXIGENT_CIRCUM,BFS_VEHICLE_INVENT,BFS_SCHOOL_POLICY,BFS_CONSENT_GIVEN,CTP_VERBAL,CTP_WRITTEN,CTP_IMPLIED,CED_NONE_CONTRABAND,CED_FIREARM,CED_AMMUNITION,CED_WEAPON,CED_DRUGS,CED_ALCOHOL,CED_MONEY,CED_DRUG_PARAPHERNALIA,CED_STOLEN_PROP,CED_ELECT_DEVICE,CED_OTHER_CONTRABAND,BPS_SAFEKEEPING,BPS_CONTRABAND,BPS_EVIDENCE,BPS_IMPOUND_VEHICLE,BPS_ABANDON_PROP,BPS_VIOLATE_SCHOOL,TPS_FIREARM,TPS_AMMUNITION,TPS_WEAPON,TPS_DRUGS,TPS_ALCOHOL,TPS_MONEY,TPS_DRUG_PARAPHERNALIA,TPS_STOLEN_PROP,TPS_CELLPHONE,TPS_VEHICLE,TPS_CONTRABAND,ROS_NO_ACTION,ROS_CITATION,ROS_IN_FIELD_CITE_RELEASE,ROS_CUSTODIAL_WARRANT,ROS_CUSTODIAL_WITHOUT_WARRANT,ROS_FIELD_INTERVIEW_CARD,ROS_NONCRIMINAL_TRANSPORT,ROS_CONTACT_LEGAL_GUARDIAN,ROS_PSYCH_HOLD,ROS_US_HOMELAND,ROS_REFERRAL_SCHOOL_ADMIN,ROS_REFERRAL_SCHOOL_COUNSELOR,ROS_WRITTEN_WARNING,ROS_VERBAL_WARNING,ROS_CITATION_CDS,ROS_IN_FIELD_CITE_RELEASE_CDS,ROS_CUSTODIAL_WOUT_WARRANT_CDS,ROS_VERBAL_WARNING_CDS,ROS_WRITTEN_WARNING_CDS,county_name
0,W389724007L72FIA0IWQ,1,CA0389700,UC-SAN FRANCISCO PD,0,10:25:00,2024-01-06,110,SAN FRANCISCO,NaN,NaN,0,0,2,1,1,50,7,0,0,1,0,0,0,0,0,1,0,2,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,32111.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,1.0000,1.0000,0.0000,0.0000,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,San Francisco
1,W389724007GDL0T2S7D2,1,CA0389700,UC-SAN FRANCISCO PD,0,19:25:00,2024-01-02,7,SAN FRANCISCO,NaN,NaN,0,0,7,1,1,45,7,0,0,1,0,0,1,0,0,1,0,2,NaN,NaN,1.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,32111.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,32111,NaN,San Francisco
2,W389724007IIE8JP4UZA,1,CA0389700,UC-SAN FRANCISCO PD,0,23:41:00,2024-01-02,10,SAN FRANCISCO,NaN,NaN,0,0,7,2,1,80,9,0,0,1,0,0,1,0,0,1,1,2,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,32100.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,32100,NaN,San Francisco
3,U380024011BB8189150F,1,CA0380000,SAN FRANCISCO CO SO,0,12:47:00,2024-01-07,22,SANTA CLARA,NaN,NaN,0,0,3,1,1,25,5,0,0,0,0,0,0,0,0,1,0,2,NaN,NaN,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,35005.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,35005,NaN,NaN,San Francisco
4,W38972400785IE076VST,1,CA0389700,UC-SAN FRANCISCO PD,0,09:59:00,2024-01-07,134,SAN FRANCISCO,NaN,NaN,0,0,1,1,1,50,7,0,0,1,0,0,0,0,0,1,0,2,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,32111.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,36222,NaN,NaN,San Francisco

In [82]:
cali_df = reduce_memory_usage(cali_df, verbose=True)

Memory usage before: 9748.80 MB
Memory usage after: 5758.58 MB
Reduced by 40.9%

In [83]:
cali_df

,DOJ_RECORD_ID,PERSON_NUMBER,AGENCY_ORI,AGENCY_NAME,NON_REPORTING_AGENCY,TIME_OF_STOP,DATE_OF_STOP,STOP_DURATION,LOC_CLOSEST_CITY,SCHOOL_CODE,SCHOOL_NAME,STOP_STUDENT,K12_SCHOOL_GROUNDS,RAE_FULL,G_FULL,SOR_STRAIGHT,AGE,AGE_GROUP,LIMITED_ENGLISH_FLUENCY,PD_FULL,PERSON_UNHOUSED,PASSENGER_IN_VEHICLE,INSIDE_RESIDENCE,WELFARE_WELLNESS_CHECK,TOS_VEHICULAR,TOS_BICYCLE,TOS_PEDESTRIAN,CALL_FOR_SERVICE,REASON_FOR_STOP,RFS_TRAFFIC_VIOLATION_TYPE,RFS_TRAFFIC_VIOLATION_CODE,RFS_RS_OFF_WITNESS,RFS_RS_MATCH_SUSPECT,RFS_RS_WITNESS_ID,RFS_RS_CARRY_SUS_OBJECT,RFS_RS_ACTIONS_INDICATIVE,RFS_RS_SUSPECT_LOOK,RFS_RS_DRUG_TRANS,RFS_RS_VIOLENT_CRIME,RFS_RS_REASON_SUSP,RFS_RS_MATCH_VEHICLE,RFS_RS_CODE,RFS_EC_DISCIPLINE_CODE,RFS_EC_DISCIPLINE,RFS_PC_OFF_WITNESS,RFS_PC_MATCH_SUSPECT,RFS_PC_WITNESS_ID,RFS_PC_CARRY_SUS_OBJECT,RFS_PC_ACTIONS_INDICATIVE,RFS_PC_SUSPECT_LOOK,RFS_PC_DRUG_TRANS,RFS_PC_VIOLENT_CRIME,RFS_PC_REASON_SUSP,RFS_PC_MATCH_VEHICLE,RFS_PC_CODE,RFS_RG_TRAFFIC_MOVING,RFS_RG_TRAFFIC_EQUIPMENT,RFS_RG_TRAFFIC_NON_MOVING,RFS_RG_OFF_WITNESS,RFS_RG_MATCH_SUSPECT,RFS_RG_MATCH_VEHICLE,RFS_RG_WITNESS_ID,RFS_RG_CARRY_SUS_OBJECT,RFS_RG_ACTIONS_INDICATIVE,RFS_RG_SUSPECT_LOOK,RFS_RG_DRUG_TRANS,RFS_RG_VIOLENT_CRIME,RFS_RG_REASON_SUSP,RFS_RG_PROBABLE_CAUSE,RFS_RG_WELFARE_AND_INST,RFS_RG_KNOWN_PAROLE,RFS_RG_OUTSTANDING_WARRANT,RFS_RG_TRUANT,RFS_RG_CONSENSUAL_SEARCH,RFS_RG_DISCIPLINE,RFS_RG_SCHOOL_POLICY,RFS_RG_NOT_COMMUNICATED,NFA_WRITTEN_STATEMENT,NFA_ASKED_SEARCH_PER,NFA_ASKED_SEARCH_PROP,NFA_ASKED_ID_PASSENGER,NFA_ASKED_PAROLE,NFA_CURB_DETENT,NFA_SOBRIETY_TEST,NFA_PATCAR_DETENT,NFA_CANINE_SEARCH,NFA_PHOTO,NFA_REMOVED_VEHICLE_ORDER,NFA_PROP_SEIZE,NFA_RAN_NAME_PASSENGER,NFA_SEARCH_PERSON,NFA_SEARCH_PROPERTY,NFA_TERRY_FRISK,NFA_VEHICLE_IMPOUND,NFA_NONE,NFA_SEARCH_PERS_CONSENT,NFA_SEARCH_PROP_CONSENT,OFA_HANDCUFFED,OFA_BATON_DRAWN,OFA_BATON_USED,OFA_CHEM_SPRAY,OFA_ELECT_DEVICE_POINT,OFA_ELECT_DEVICE_STUN,OFA_ELECT_DEVICE_DART,OFA_FIREARM_UNHOLSTERED,OFA_FIREARM_POINT,OFA_FIREARM_DISCHARGE,OFA_IMPACT_PROJECTILE_POINT,OFA_IMPACT_PROJECTILE_DISCHARGE,OFA_CANINE_COMPLIANCE,OFA_CANINE_BITE,OFA_REMOVED_VEHICLE_PHYCONTACT,OFA_PHYSICAL_COMPLIANCE,OFA_USE_VEHICLE,OFA_NONE,BFS_OFFICER_SAFETY,BFS_SEARCH_WARRANT,BFS_PAROLE,BFS_SUSPECT_WEAPON,BFS_VISIBLE_CONTRABAND,BFS_ODOR_CONTRABAND,BFS_CANINE_DETECT,BFS_EVIDENCE,BFS_INCIDENT,BFS_EXIGENT_CIRCUM,BFS_VEHICLE_INVENT,BFS_SCHOOL_POLICY,BFS_CONSENT_GIVEN,CTP_VERBAL,CTP_WRITTEN,CTP_IMPLIED,CED_NONE_CONTRABAND,CED_FIREARM,CED_AMMUNITION,CED_WEAPON,CED_DRUGS,CED_ALCOHOL,CED_MONEY,CED_DRUG_PARAPHERNALIA,CED_STOLEN_PROP,CED_ELECT_DEVICE,CED_OTHER_CONTRABAND,BPS_SAFEKEEPING,BPS_CONTRABAND,BPS_EVIDENCE,BPS_IMPOUND_VEHICLE,BPS_ABANDON_PROP,BPS_VIOLATE_SCHOOL,TPS_FIREARM,TPS_AMMUNITION,TPS_WEAPON,TPS_DRUGS,TPS_ALCOHOL,TPS_MONEY,TPS_DRUG_PARAPHERNALIA,TPS_STOLEN_PROP,TPS_CELLPHONE,TPS_VEHICLE,TPS_CONTRABAND,ROS_NO_ACTION,ROS_CITATION,ROS_IN_FIELD_CITE_RELEASE,ROS_CUSTODIAL_WARRANT,ROS_CUSTODIAL_WITHOUT_WARRANT,ROS_FIELD_INTERVIEW_CARD,ROS_NONCRIMINAL_TRANSPORT,ROS_CONTACT_LEGAL_GUARDIAN,ROS_PSYCH_HOLD,ROS_US_HOMELAND,ROS_REFERRAL_SCHOOL_ADMIN,ROS_REFERRAL_SCHOOL_COUNSELOR,ROS_WRITTEN_WARNING,ROS_VERBAL_WARNING,ROS_CITATION_CDS,ROS_IN_FIELD_CITE_RELEASE_CDS,ROS_CUSTODIAL_WOUT_WARRANT_CDS,ROS_VERBAL_WARNING_CDS,ROS_WRITTEN_WARNING_CDS,county_name
0,W389724007L72FIA0IWQ,1,CA0389700,UC-SAN FRANCISCO PD,0,10:25:00,2024-01-06,110,SAN FRANCISCO,NaN,NaN,0,0,2,1,1,50,7,0,0,1,0,0,0,0,0,1,0,2,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,32111.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,1.0000,1.0000,0.0000,0.0000,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,San Francisco
1,W389724007GDL0T2S7D2,1,CA0389700,UC-SAN FRANCISCO PD,0,19:25:00,2024-01-02,7,SAN FRANCISCO,NaN,NaN,0,0,7,1,1,45,7,0,0,1,0,0,1,0,0,1,0,2,NaN,NaN,1.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,32111.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,32111,NaN,San Francisco
2,W389724007IIE8JP4UZA,1,CA0389700,UC-SAN FRANCISCO PD,0,23:41:00,2024-01-02,10,SAN FRANCISCO,NaN,NaN,0,0,7,2,1,80,9,0,0,1,0,0,1,0,0,1,1,2,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,32100.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,32100,NaN,San Francisco
3,U380024011BB8189150F,1,CA0380000,SAN FRANCISCO CO SO,0,12:47:00,2024-01-07,22,SANTA CLARA,NaN,NaN,0,0,3,1,1,25,5,0,0,0,0,0,0,0,0,1,0,2,NaN,NaN,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,35005.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,35005,NaN,NaN,San Francisco
4,W38972400785IE076VST,1,CA0389700,UC-SAN FRANCISCO PD,0,09:59:00,2024-01-07,134,SAN FRANCISCO,NaN,NaN,0,0,1,1,1,50,7,0,0,1,0,0,0,0,0,1,0,2,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,32111.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,36222,NaN,NaN,San Francisco
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5065423,S290125091P1W7ZF8M5R,2,CA0290100,GRASS VALLEY PD,0,23:51:00,2024-09-21,8,NEVADA CITY,NaN,NaN,0,0,7,1,1,60,8,0,0,0,1,0,0,1,0,0,0,1,3.0000,54657.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,54657,NaN,Nevada
5065424,S290125091GE91EUNDWN,1,CA0290100,GRASS VALLEY PD,0,18:50:00,2024-09-24,4,GRASS VALLEY,NaN,NaN,0,0,7,1,1,34,5,0,0,1,0,0,0,0,0,1,1,2,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,35143.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,32082,NaN,Nevada
5065425,S290125091GE91EUNDWN,2,CA0290100,GRASS VALLEY PD,0,18:50:00,2024-09-24,4,GRASS VALLEY,NaN,NaN,0,0,7,2,1,55,8,0,0,1,0,0,0,0,0,1,1,2,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,35143.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,32082,NaN,Nevada
5065426,S290125091AVHQTN7ME9,1,CA0290100,GRASS VALLEY PD,0,20:16:00,2024-09-17,51,GRASS VALLEY,NaN,NaN,0,0,7,1,1,40,6,0,0,1,0,0,0,0,0,1,1,2,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,35423.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,Nevada
5065427,S290125091AVHQTN7ME9,2,CA0290100,GRASS VALLEY PD,0,20:16:00,2024-09-17,51,GRASS VALLEY,NaN,NaN,0,0,7,1,1,38,6,0,0,1,0,0,0,0,0,1,1,2,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,35423.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,Nevada

# Concating DataFrames

## Cleaning Each DF

In [84]:
standard_cols = [
    "date", 
    "agency_name" ,
    "ori",
    "state",
    "location",
    "subject_race",
    "subject_age",
    "subject_gender" ,
    "force_used",
    "indication_of_injury" ,
    "incident_id"
]

### NJ

In [85]:
nj_df.head(1).T

                                                                 0
Form ID                                                     866515
County                                                       Ocean
Agency Name                                        Berkeley Twp PD
Officer Name                                     Michael Bulwinski
User ID                                                 10818.0000
Incident ID                        OCEAN-BERKELEY TWP PD-23-003647
Report Number                                          UOF23-11-52
Incident Case Number                                     23-003647
Incident Date                                            11/6/2023
Other Officer Involved                                Not Provided
Officer In Uniform                                            True
Incident Municipality                       Berkeley, Ocean County
Indoor Or Outdoor                                         Outdoors
Incident Weather                                             Clear
Video Footage                                                  Yes
Video Type                                               Body Worn
Incident Lighting                                         Darkness
Location Type                                               Street
Incident Type                                              Assault
Contact Origin                                          Dispatched
Planned Contact                                                NaN
Officer Age                                                     33
Officer Race/Ethnicity                                       White
Officer Rank                                               Officer
Officer Gender                                                Male
Officer Injury Type                                    Not injured
Officer Injuries Injured                                     FALSE
Officer Medical Treatment                                      NaN
Officer Hospital Treatment                                     NaN
Total Sub Injured In Incident                               0.0000
Subject Injured In Incident                                     No
Subject Injured Prior To Incident                          Unknown
Perceived Condition Of Subject          No unusual condition noted
Subject Actions                     Attempt to escape from Custody
Subject Resistance                                Passive Resistor
Subject Medical Treatment                                      NaN
Subject Injury Type                                            NaN
Subject Arrested                                              TRUE
Reason Subject Not Arrested                                    NaN
Subject Type                                                Person
Subject Age                                                     28
Subject Race/Ethnicity                                    Hispanic
Subject Gender                                                Male
Force Type                                       Used take down on
Incident Year                                                 2023
KEEP/DROP                                                     KEEP

In [86]:
nj_df.columns

Index(['Form ID', 'County', 'Agency Name', 'Officer Name', 'User ID',
       'Incident ID', 'Report Number', 'Incident Case Number', 'Incident Date',
       'Other Officer Involved', 'Officer In Uniform', 'Incident Municipality',
       'Indoor Or Outdoor', 'Incident Weather', 'Video Footage', 'Video Type',
       'Incident Lighting', 'Location Type', 'Incident Type', 'Contact Origin',
       'Planned Contact', 'Officer Age', 'Officer Race/Ethnicity',
       'Officer Rank', 'Officer Gender', 'Officer Injury Type',
       'Officer Injuries Injured', 'Officer Medical Treatment',
       'Officer Hospital Treatment', 'Total Sub Injured In Incident',
       'Subject Injured In Incident', 'Subject Injured Prior To Incident',
       'Perceived Condition Of Subject', 'Subject Actions',
       'Subject Resistance', 'Subject Medical Treatment',
       'Subject Injury Type', 'Subject Arrested',
       'Reason Subject Not Arrested', 'Subject Type', 'Subject Age',
       'Subject Race/Ethnicity', 'Subject Gender', 'Force Type',
       'Incident Year', 'KEEP/DROP'],
      dtype='str')

In [87]:
nj_cols_to_keep = [
    'Form ID', 'County', 'Agency Name', 'Incident ID', 'Report Number', 'Incident Case Number', 'Incident Date', 'Incident Type', 
    'Subject Actions',
    'Subject Resistance', 'Subject Medical Treatment',
    'Subject Injury Type', 'Subject Arrested',
    'Reason Subject Not Arrested', 'Subject Type', 'Subject Age',
    'Subject Race/Ethnicity', 'Subject Gender', 'Force Type'
]
nj_df = nj_df[nj_cols_to_keep]

In [88]:
nj_df = nj_df.add_prefix("NJ_")

nj_df = (
    nj_df.assign(
        date = lambda x: x["NJ_Incident Date"],
        agency_name = lambda x: x["NJ_Agency Name"],
        ori = None,
        location = lambda x: x["NJ_County"],
        subject_race = lambda x: x["NJ_Subject Race/Ethnicity"],
        subject_age = lambda x: x["NJ_Subject Age"],
        subject_gender = lambda x: x["NJ_Subject Gender"],
        force_used = lambda x: x["NJ_Force Type"],
        indication_of_injury = None,
        incident_id = lambda x: x[["NJ_Incident ID", "NJ_Report Number", "NJ_Incident Case Number"]].apply(
                lambda row: [str(v) for v in row if pd.notna(v)],
                axis=1
            ))
)
nj_df.head()

,NJ_Form ID,NJ_County,NJ_Agency Name,NJ_Incident ID,NJ_Report Number,NJ_Incident Case Number,NJ_Incident Date,NJ_Incident Type,NJ_Subject Actions,NJ_Subject Resistance,NJ_Subject Medical Treatment,NJ_Subject Injury Type,NJ_Subject Arrested,NJ_Reason Subject Not Arrested,NJ_Subject Type,NJ_Subject Age,NJ_Subject Race/Ethnicity,NJ_Subject Gender,NJ_Force Type,date,agency_name,ori,location,subject_race,subject_age,subject_gender,force_used,indication_of_injury,incident_id
0,866515,Ocean,Berkeley Twp PD,OCEAN-BERKELEY TWP PD-23-003647,UOF23-11-52,23-003647,11/6/2023,Assault,Attempt to escape from Custody,Passive Resistor,NaN,NaN,TRUE,NaN,Person,28,Hispanic,Male,Used take down on,11/6/2023,Berkeley Twp PD,None,Ocean,Hispanic,28,Male,Used take down on,None,"[OCEAN-BERKELEY TWP PD-23-003647, UOF23-11-52,..."
1,91681,Ocean,Toms River Twp PD,OCEAN-TOMS RIVER TWP PD-21-20078,UOF21-5-48,21-20078,5/13/2021,"Welfare Check, Potential Mental Health Incident","Resisted arrest/police officer control, Verbal...","Verbal, Resistive tension (stiffening, tigheni...",NaN,NaN,FALSE,Medical/Mental Health Incident,Person,55,White,Female,Used arms,5/13/2021,Toms River Twp PD,None,Ocean,White,55,Female,Used arms,None,"[OCEAN-TOMS RIVER TWP PD-21-20078, UOF21-5-48,..."
2,50307,Cumberland,Vineland PD,CUMBERLAND-VINELAND PD-2021-4288,UOF21-1-19,2021-4288,1/27/2021,MV/Traffic Stop,"Resisted arrest/police officer control, Attack...","Resistive tension (stiffening, tighening muscl...","EMS on scene, Hospital",Abrasion/Laceration/Puncture,TRUE,NaN,Person,37,Hispanic,Male,Canine bit (apprehension),1/27/2021,Vineland PD,None,Cumberland,Hispanic,37,Male,Canine bit (apprehension),None,"[CUMBERLAND-VINELAND PD-2021-4288, UOF21-1-19,..."
3,201634,Ocean,Lakewood PD,OCEAN-LAKEWOOD PD-22-001779,UOF22-1-9,22-001779,1/8/2022,Medical Emergency,"Strike with open hand, fist, or elbow",Active Resistor,NaN,NaN,FALSE,Medical/Mental Health Incident,Person,35,Hispanic,Female,Used arms/hands,1/8/2022,Lakewood PD,None,Ocean,Hispanic,35,Female,Used arms/hands,None,"[OCEAN-LAKEWOOD PD-22-001779, UOF22-1-9, 22-00..."
4,1594362,Bergen,Rutherford PD,BERGEN-RUTHERFORD PD-25-08463,UOF25-5-1,25-08463,5/11/2025,Theft/Shoplifting,Attempt to escape from Custody,Active Resistor,NaN,NaN,TRUE,NaN,Person,19,Hispanic,Male,Used take down on,5/11/2025,Rutherford PD,None,Bergen,Hispanic,19,Male,Used take down on,None,"[BERGEN-RUTHERFORD PD-25-08463, UOF25-5-1, 25-..."

In [89]:
print(nj_df.shape)

(97877, 29)

### Ohio

In [90]:
ohio_df.head(1).T

                                                                                0
AgencyName                                                                  Akron
IncidentNumber                                                       202400000028
IncidentDate                                                             1/1/2024
InitialContactCircumstances              Unknown and is Unlikely to Ever be Known
LocationType                             Unknown And Is Unlikely To Ever Be Known
SubjectResistanceTypes          Failing to Comply to Verbal Commands | Pulling...
SubjectArmed/BelievedToBeArmed                                                 No
SubjectRaceEthnicity                                                        White
SubjectGender                                                                Male
SubjectInjuries                                                               NaN
SubjectImpairments                                                            NaN
OfficerType                                                       Law Enforcement
OfficerResponse/ForceTypes      Other Force Type Used | Restraining Hold | Oth...
OfficerRaceEthnicity                                                White | White
OfficerGender                                                       Female | Male
OfficerInjuries                                      Apparent Minor Injury | None

In [91]:
ohio_df = ohio_df.add_prefix("Ohio_")

ohio_df = (
    ohio_df.assign(
        date = lambda x: x["Ohio_IncidentDate"],
        agency_name = lambda x: x["Ohio_AgencyName"],
        ori = None,
        location = lambda x: x["Ohio_AgencyName"],
        subject_race = lambda x: x["Ohio_SubjectRaceEthnicity"],
        subject_age = None,
        subject_gender = lambda x: x["Ohio_SubjectGender"],
        force_used = lambda x: x["Ohio_OfficerResponse/ForceTypes"],
        indication_of_injury = lambda x: x["Ohio_SubjectInjuries"],
        incident_id = lambda x: x[["Ohio_IncidentNumber"]].apply(
                lambda row: [str(v) for v in row if pd.notna(v)],
                axis=1
            ))
)
ohio_df.head()

,Ohio_AgencyName,Ohio_IncidentNumber,Ohio_IncidentDate,Ohio_InitialContactCircumstances,Ohio_LocationType,Ohio_SubjectResistanceTypes,Ohio_SubjectArmed/BelievedToBeArmed,Ohio_SubjectRaceEthnicity,Ohio_SubjectGender,Ohio_SubjectInjuries,Ohio_SubjectImpairments,Ohio_OfficerType,Ohio_OfficerResponse/ForceTypes,Ohio_OfficerRaceEthnicity,Ohio_OfficerGender,Ohio_OfficerInjuries,date,agency_name,ori,location,subject_race,subject_age,subject_gender,force_used,indication_of_injury,incident_id
0,Akron,202400000028,1/1/2024,Unknown and is Unlikely to Ever be Known,Unknown And Is Unlikely To Ever Be Known,Failing to Comply to Verbal Commands | Pulling...,No,White,Male,NaN,NaN,Law Enforcement,Other Force Type Used | Restraining Hold | Oth...,White | White,Female | Male,Apparent Minor Injury | None,1/1/2024,Akron,None,Akron,White,None,Male,Other Force Type Used | Restraining Hold | Oth...,NaN,[202400000028]
1,Ravenna,2240010006,1/1/2024,Other Circumstances,Government Office,Verbally Threatening Others,No,White,Male,NaN,Alcohol Impairment,Law Enforcement,Restraining Hold,White | White,Male | Male,NaN,1/1/2024,Ravenna,None,Ravenna,White,None,Male,Restraining Hold,NaN,[2240010006]
2,Holland,24-000001-1,1/1/2024,Responding to Other Unlawful or Suspicious Act...,Single Family Home,Failing to Comply to Verbal Commands | Resisti...,No,Black or African American,Male,NaN,NaN,Law Enforcement,Balance Displacement | Electronic Control Devi...,White | White,Male | Male,NaN,1/1/2024,Holland,None,Holland,Black or African American,None,Male,Balance Displacement | Electronic Control Devi...,NaN,[24-000001-1]
3,Holland,24-000001-1,1/1/2024,Responding to Other Unlawful or Suspicious Act...,Single Family Home,Failing to Comply to Verbal Commands | Resisti...,No,Black or African American,Male,NaN,NaN,Law Enforcement,Balance Displacement | Electronic Control Devi...,White | White,Male | Male,NaN,1/1/2024,Holland,None,Holland,Black or African American,None,Male,Balance Displacement | Electronic Control Devi...,NaN,[24-000001-1]
4,Woodlawn,202400000001,1/1/2024,Traffic Stop,Single Family Home,Firearm Displayed at an Officer or Another,Yes,Black or African American,Female,NaN,NaN,Law Enforcement,Other Force Type Used,Black or African American | White,Male | Male,NaN,1/1/2024,Woodlawn,None,Woodlawn,Black or African American,None,Female,Other Force Type Used,NaN,[202400000001]

In [92]:
ohio_df

,Ohio_AgencyName,Ohio_IncidentNumber,Ohio_IncidentDate,Ohio_InitialContactCircumstances,Ohio_LocationType,Ohio_SubjectResistanceTypes,Ohio_SubjectArmed/BelievedToBeArmed,Ohio_SubjectRaceEthnicity,Ohio_SubjectGender,Ohio_SubjectInjuries,Ohio_SubjectImpairments,Ohio_OfficerType,Ohio_OfficerResponse/ForceTypes,Ohio_OfficerRaceEthnicity,Ohio_OfficerGender,Ohio_OfficerInjuries,date,agency_name,ori,location,subject_race,subject_age,subject_gender,force_used,indication_of_injury,incident_id
0,Akron,202400000028,1/1/2024,Unknown and is Unlikely to Ever be Known,Unknown And Is Unlikely To Ever Be Known,Failing to Comply to Verbal Commands | Pulling...,No,White,Male,NaN,NaN,Law Enforcement,Other Force Type Used | Restraining Hold | Oth...,White | White,Female | Male,Apparent Minor Injury | None,1/1/2024,Akron,None,Akron,White,None,Male,Other Force Type Used | Restraining Hold | Oth...,NaN,[202400000028]
1,Ravenna,2240010006,1/1/2024,Other Circumstances,Government Office,Verbally Threatening Others,No,White,Male,NaN,Alcohol Impairment,Law Enforcement,Restraining Hold,White | White,Male | Male,NaN,1/1/2024,Ravenna,None,Ravenna,White,None,Male,Restraining Hold,NaN,[2240010006]
2,Holland,24-000001-1,1/1/2024,Responding to Other Unlawful or Suspicious Act...,Single Family Home,Failing to Comply to Verbal Commands | Resisti...,No,Black or African American,Male,NaN,NaN,Law Enforcement,Balance Displacement | Electronic Control Devi...,White | White,Male | Male,NaN,1/1/2024,Holland,None,Holland,Black or African American,None,Male,Balance Displacement | Electronic Control Devi...,NaN,[24-000001-1]
3,Holland,24-000001-1,1/1/2024,Responding to Other Unlawful or Suspicious Act...,Single Family Home,Failing to Comply to Verbal Commands | Resisti...,No,Black or African American,Male,NaN,NaN,Law Enforcement,Balance Displacement | Electronic Control Devi...,White | White,Male | Male,NaN,1/1/2024,Holland,None,Holland,Black or African American,None,Male,Balance Displacement | Electronic Control Devi...,NaN,[24-000001-1]
4,Woodlawn,202400000001,1/1/2024,Traffic Stop,Single Family Home,Firearm Displayed at an Officer or Another,Yes,Black or African American,Female,NaN,NaN,Law Enforcement,Other Force Type Used,Black or African American | White,Male | Male,NaN,1/1/2024,Woodlawn,None,Woodlawn,Black or African American,None,Female,Other Force Type Used,NaN,[202400000001]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3253,Wooster,24-75026,9/9/2024,Responding to Other Unlawful or Suspicious Act...,Street,Failing to Comply to Verbal Commands | Resisti...,No,White,Male,NaN,Drug Impairment | Mental Health Condition,Law Enforcement,Restraining Hold | Take Down,White,Male,NaN,9/9/2024,Wooster,None,Wooster,White,None,Male,Restraining Hold | Take Down,NaN,[24-75026]
3254,Liberty Township,24-0009655,9/9/2024,Routine Patrol/On-view (Other than Traffic),Parking Lot,Attempt to Escape/Flee From Custody | Failing ...,Yes,Black or African American,Male,NaN,NaN,Law Enforcement,Restraining Hold | Take Down,Unknown/Not Reported,Pending Further Investigation,NaN,9/9/2024,Liberty Township,None,Liberty Township,Black or African American,None,Male,Restraining Hold | Take Down,NaN,[24-0009655]
3255,Cleveland,2024-265997,9/9/2024,Unknown and is Unlikely to Ever be Known,Unknown And Is Unlikely To Ever Be Known,Pulling Away | Resisting Being Handcuffed or A...,Unknown and is Unlikely to Ever be Known,Black or African American,Female,NaN,NaN,Law Enforcement,Balance Displacement | Restraining Hold,Black or African American | White,Male | Female,NaN,9/9/2024,Cleveland,None,Cleveland,Black or African American,None,Female,Balance Displacement | Restraining Hold,NaN,[2024-265997]
3256,Zanesville,24-020795,9/9/2024,Responding to Other Unlawful or Suspicious Act...,Single Family Home,Attempt to Escape/Flee From Custody | Deadweig...,No,White,Male,Apparent Minor Injury,NaN,Law Enforcement,Balance Displacement | Restraining Hold | Pres...,White | White | White | White,Male | Male | Male | Male,NaN,9/9/2024,Zanesville,None,Zanesville,White,None,Male,Balance Displacement | Restraining Hold | Pres...,Apparent Minor Injury,[24-020795]
3257,University of Toledo,00044824,9/9/2024,Responding to Other Unlawful or Suspicious Act...,Street,Attempt to Escape/Flee From Custody,No,Black or African American,Male,NaN,NaN,Law Enforcement,Other Force Type Used,White,Male,NaN,9/9/2024,University of Toledo,None,University of Toledo,Black or African American,None,Male,Other Force Type Used,NaN,[00044824]

### NY

In [93]:
ny_df.head(1).T

                                                0
TRI Incident Number                 2024032962162
ForceType                          Physical Force
Occurrence Date                        08/31/2024
Incident Pct                                   13
Patrol Borough                               PBMS
YearMonthShort                           2024 Aug
BasisForEncounter     CRIME/VIOLATION IN PROGRESS
Subject Injury Level                    No Injury
Subject Injured                                 N
Age                                       17.0000
Subject Race                                BLACK
Subject Gender                               MALE
Force Against MOS                  Physical Force
Subject Used Force                              Y

In [94]:
ny_df = ny_df.add_prefix("NY_")

In [95]:
ny_df = (
    ny_df.assign(
        date = lambda x: x["NY_Occurrence Date"],
        agency_name = lambda x: x["NY_Incident Pct"],
        ori = None,
        location = lambda x: x["NY_Patrol Borough"],
        subject_race = lambda x: x["NY_Subject Race"],
        subject_age = lambda x: x["NY_Age"],
        subject_gender = lambda x: x["NY_Subject Gender"],
        force_used = lambda x: x["NY_ForceType"],
        indication_of_injury = lambda x: x["NY_Subject Injured"],
        incident_id = lambda x: x[["NY_TRI Incident Number"]].apply(
                lambda row: [str(v) for v in row if pd.notna(v)],
                axis=1
            ))
)
ny_df.head()

,NY_TRI Incident Number,NY_ForceType,NY_Occurrence Date,NY_Incident Pct,NY_Patrol Borough,NY_YearMonthShort,NY_BasisForEncounter,NY_Subject Injury Level,NY_Subject Injured,NY_Age,NY_Subject Race,NY_Subject Gender,NY_Force Against MOS,NY_Subject Used Force,date,agency_name,ori,location,subject_race,subject_age,subject_gender,force_used,indication_of_injury,incident_id
0,2024032962162,Physical Force,08/31/2024,13,PBMS,2024 Aug,CRIME/VIOLATION IN PROGRESS,No Injury,N,17.0000,BLACK,MALE,Physical Force,Y,08/31/2024,13,None,PBMS,BLACK,17.0000,MALE,Physical Force,N,[2024032962162]
1,2024033962356,Physical Force,08/31/2024,14,PBMS,2024 Aug,CRIME/VIOLATION IN PROGRESS,No Injury,N,30.0000,BLACK,MALE,Physical Force,Y,08/31/2024,14,None,PBMS,BLACK,30.0000,MALE,Physical Force,N,[2024033962356]
2,2024090962120,Physical Force,08/31/2024,71,PBBS,2024 Aug,CRIME/VIOLATION IN PROGRESS,No Injury,N,19.0000,OTHER,MALE,Physical Force,Y,08/31/2024,71,None,PBBS,OTHER,19.0000,MALE,Physical Force,N,[2024090962120]
3,2024096962122,Physical Force,08/31/2024,77,PBBN,2024 Aug,CRIME/VIOLATION IN PROGRESS,No Injury,N,38.0000,BLACK,MALE,Physical Force,Y,08/31/2024,77,None,PBBN,BLACK,38.0000,MALE,Physical Force,N,[2024096962122]
4,2024081962083,Physical Force,08/31/2024,62,PBBS,2024 Aug,CRIME/VIOLATION IN PROGRESS,Physical Injury,Y,17.0000,HISPANIC,MALE,Physical Force,Y,08/31/2024,62,None,PBBS,HISPANIC,17.0000,MALE,Physical Force,Y,[2024081962083]

In [96]:
ny_df["force_used"].isna().sum()

np.int64(0)

In [97]:
ny_uof_long = ny_uof_long.add_prefix("NY_")

In [98]:
ny_uof_long["NY_subject_ethnicity"] = ny_uof_long["NY_subject_ethnicity"].fillna(ny_uof_long["NY_subject_race"])

In [99]:
ny_uof_long["NY_subject_ethnicity"].info()

<class 'pandas.Series'>
Index: 42881 entries, 0 to 870900
Series name: NY_subject_ethnicity
Non-Null Count  Dtype
--------------  -----
42881 non-null  str
dtypes: str(1)
memory usage: 670.0 KB

In [100]:
ny_uof_long.head(1).T

                                                                                              0
NY_incident_id                                                                                0
NY_Response ID\n(5/16/25 File)                                                                1
NY_Agency Name                                                                      Akron Vg PD
NY_Incident Date                                                            2020-12-22 00:00:00
NY_City/town/village (location Where Incident O...                                        Akron
NY_County (location where incident occurred)                                               Erie
NY_Circumstance                                     Response to unlawful or suspicious activity
NY_Officer 1 - Use of Force Type                                                Pointed Firearm
NY_Officer 1 Age                                                                        27.0000
NY_Officer 1 Sex                                                                           Male
NY_Officer 1 Race                                                                         White
NY_Officer 1 Ethnicity                                                             Non-Hispanic
NY_Officer 2 - Use of Force Type                                                            NaN
NY_Officer 2 Age                                                                            NaN
NY_Officer 2 Sex                                                                            NaN
NY_Officer 2 Race                                                                           NaN
NY_Officer 2 Ethnicity                                                                      NaN
NY_Officer 3 - Use of Force Type                                                            NaN
NY_Officer 3 Age                                                                            NaN
NY_Officer 3 Sex                                                                            NaN
NY_Officer 3 Race                                                                           NaN
NY_Officer 3 Ethnicity                                                                      NaN
NY_Officer 4 - Use of Force Type                                                            NaN
NY_Officer 4 Age                                                                            NaN
NY_Officer 4 Sex                                                                            NaN
NY_Officer 4 Race                                                                           NaN
NY_Officer 4 Ethnicity                                                                      NaN
NY_Officer 5 - Use of Force Type                                                            NaN
NY_Officer 5 Age                                                                            NaN
NY_Officer 5 Sex                                                                            NaN
NY_Officer 5 Race                                                                           NaN
NY_Officer 5 Ethnicity                                                                      NaN
NY_Officer 6 - Use of Force Type                                                            NaN
NY_Officer 6 Age                                                                            NaN
NY_Officer 6 Sex                                                                            NaN
NY_Officer 6 Race                                                                           NaN
NY_Officer 6 Ethnicity                                                                      NaN
NY_Officer 7 - Use of Force Type                                                            NaN
NY_Officer 7 Age                                                                            NaN
NY_Officer 7 Sex                                                                            NaN
NY_Officer 7 Race                                                                           NaN
NY_Officer 7 Ethnicity                                                                      NaN
NY_Officer 8 - Use of Force Type                                                            NaN
NY_Officer 8 Age                                                                            NaN
NY_Officer 8 Sex                                                                            NaN
NY_Officer 8 Race                                                                           NaN
NY_Officer 8 Ethnicity                                                                      NaN
NY_Officer 9 - Use of Force Type                                                            NaN
NY_Officer 9 Age                                                                            NaN
NY_Officer 9 Sex                                                                            NaN
NY_Officer 9 Race                                                                           NaN
NY_Officer 9 Ethnicity                                                                      NaN
NY_Officer 10 - Use of Force Type                                                           NaN
NY_Officer 10 Age                                                                           NaN
NY_Officer 10 Sex                                                                           NaN
NY_Officer 10 Race                                                                          NaN
NY_Officer 10 Ethnicity                                                                     NaN
NY_Officer 11 - Use of Force Type                                                           NaN
NY_Officer 11 Age                                                                           NaN
NY_Officer 11 Sex                                                                           NaN
NY_Officer 11 Race                                                                          NaN
NY_Officer 11 Ethnicity                                                                     NaN
NY_Officer 12 - Use of Force Type                                                           NaN
NY_Officer 12 Age                                                                           NaN
NY_Officer 12 Sex                                                                           NaN
NY_Officer 12 Race                                                                          NaN
NY_Officer 12 Ethnicity                                                                     NaN
NY_Officer 13 - Use of Force Type                                                           NaN
NY_Officer 13 Age                                                                           NaN
NY_Officer 13 Sex                                                                           NaN
NY_Officer 13 Race                                                                          NaN
NY_Officer 13 Ethnicity                                                                     NaN
NY_Officer 14 - Use of Force Type                                                           NaN
NY_Officer 14 Age                                                                           NaN
NY_Officer 14 Sex                                                                           NaN
NY_Officer 14 Race                                                                          NaN
NY_Officer 14 Ethnicity                                                                     NaN
NY_Officer 15 - Use of Force Type                                                           NaN
NY_Officer 15 Age                                                                           NaN
NY_Officer 15 Sex                                                                           NaN
NY_Officer 15 Race                                                                          NaN
NY_Officer 15 Ethnicity                                                                     NaN
NY_Officer 16 - Use of Force Type                                                           NaN
NY_Officer 16 Age                                                                           NaN
NY_Officer 16 Sex                                                                           NaN
NY_Officer 16 Race                                                                          NaN
NY_Officer 16 Ethnicity                                                                     NaN
NY_subject_number                                                                             1
NY_subject_race                                                                           White
NY_subject_ethnicity                                                               Non-Hispanic
NY_subject_age                                                                          49.0000
NY_subject_sex                                                                             Male

In [101]:
ny_long_force_cols = [c for c in ny_uof_long.columns if "Use of Force Type" in c]
ny_long_force_cols

['NY_Officer 1 - Use of Force Type',
 'NY_Officer 2 - Use of Force Type',
 'NY_Officer 3 - Use of Force Type',
 'NY_Officer 4 - Use of Force Type',
 'NY_Officer 5 - Use of Force Type',
 'NY_Officer 6 - Use of Force Type',
 'NY_Officer 7 - Use of Force Type',
 'NY_Officer 8 - Use of Force Type',
 'NY_Officer 9 - Use of Force Type',
 'NY_Officer 10 - Use of Force Type',
 'NY_Officer 11 - Use of Force Type',
 'NY_Officer 12 - Use of Force Type',
 'NY_Officer 13 - Use of Force Type',
 'NY_Officer 14 - Use of Force Type',
 'NY_Officer 15 - Use of Force Type',
 'NY_Officer 16 - Use of Force Type']

In [102]:
ny_uof_long.shape

(42881, 92)

In [103]:
(
    ny_uof_long.assign(
        date = lambda x: x["NY_Incident Date"],
        agency_name = lambda x: x["NY_Agency Name"],
        ori = None,
        location = lambda x: x["NY_City/town/village (location Where Incident Occurred)"] + ", " + x["NY_County (location where incident occurred)"],
        subject_race = lambda x: x["NY_subject_race"],
        subject_age = lambda x: x["NY_subject_age"],
        subject_gender = lambda x: x["NY_subject_sex"],
        force_used = lambda x: x[ny_long_force_cols].apply(
            lambda row: ' | '.join([
                str(row[col]) for col in ny_long_force_cols 
                if (not pd.isna(row[col])) and (str(row[col]).strip() != "") and (str(row[col]).lower() != "nan" and str(row[col]) != "0")
            ]), axis=1
        ),
        indication_of_injury = None,
        incident_id = lambda x: x[["NY_Response ID\n(5/16/25 File)"]]
    )
)

,NY_incident_id,NY_Response ID\n(5/16/25 File),NY_Agency Name,NY_Incident Date,NY_City/town/village (location Where Incident Occurred),NY_County (location where incident occurred),NY_Circumstance,NY_Officer 1 - Use of Force Type,NY_Officer 1 Age,NY_Officer 1 Sex,NY_Officer 1 Race,NY_Officer 1 Ethnicity,NY_Officer 2 - Use of Force Type,NY_Officer 2 Age,NY_Officer 2 Sex,NY_Officer 2 Race,NY_Officer 2 Ethnicity,NY_Officer 3 - Use of Force Type,NY_Officer 3 Age,NY_Officer 3 Sex,NY_Officer 3 Race,NY_Officer 3 Ethnicity,NY_Officer 4 - Use of Force Type,NY_Officer 4 Age,NY_Officer 4 Sex,NY_Officer 4 Race,NY_Officer 4 Ethnicity,NY_Officer 5 - Use of Force Type,NY_Officer 5 Age,NY_Officer 5 Sex,NY_Officer 5 Race,NY_Officer 5 Ethnicity,NY_Officer 6 - Use of Force Type,NY_Officer 6 Age,NY_Officer 6 Sex,NY_Officer 6 Race,NY_Officer 6 Ethnicity,NY_Officer 7 - Use of Force Type,NY_Officer 7 Age,NY_Officer 7 Sex,NY_Officer 7 Race,NY_Officer 7 Ethnicity,NY_Officer 8 - Use of Force Type,NY_Officer 8 Age,NY_Officer 8 Sex,NY_Officer 8 Race,NY_Officer 8 Ethnicity,NY_Officer 9 - Use of Force Type,NY_Officer 9 Age,NY_Officer 9 Sex,NY_Officer 9 Race,NY_Officer 9 Ethnicity,NY_Officer 10 - Use of Force Type,NY_Officer 10 Age,NY_Officer 10 Sex,NY_Officer 10 Race,NY_Officer 10 Ethnicity,NY_Officer 11 - Use of Force Type,NY_Officer 11 Age,NY_Officer 11 Sex,NY_Officer 11 Race,NY_Officer 11 Ethnicity,NY_Officer 12 - Use of Force Type,NY_Officer 12 Age,NY_Officer 12 Sex,NY_Officer 12 Race,NY_Officer 12 Ethnicity,NY_Officer 13 - Use of Force Type,NY_Officer 13 Age,NY_Officer 13 Sex,NY_Officer 13 Race,NY_Officer 13 Ethnicity,NY_Officer 14 - Use of Force Type,NY_Officer 14 Age,NY_Officer 14 Sex,NY_Officer 14 Race,NY_Officer 14 Ethnicity,NY_Officer 15 - Use of Force Type,NY_Officer 15 Age,NY_Officer 15 Sex,NY_Officer 15 Race,NY_Officer 15 Ethnicity,NY_Officer 16 - Use of Force Type,NY_Officer 16 Age,NY_Officer 16 Sex,NY_Officer 16 Race,NY_Officer 16 Ethnicity,NY_subject_number,NY_subject_race,NY_subject_ethnicity,NY_subject_age,NY_subject_sex,date,agency_name,ori,location,subject_race,subject_age,subject_gender,force_used,indication_of_injury,incident_id
0,0,1,Akron Vg PD,2020-12-22,Akron,Erie,Response to unlawful or suspicious activity,Pointed Firearm,27.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,White,Non-Hispanic,49.0000,Male,2020-12-22,Akron Vg PD,None,"Akron, Erie",White,49.0000,Male,Pointed Firearm,None,1
25,1,2,Albany City PD,2020-11-10,Albany,Albany,Other,Used/Deployed Chemical Agent,37.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,NaN,Male,2020-11-10,Albany City PD,None,"Albany, Albany",Black,NaN,Male,Used/Deployed Chemical Agent,None,2
50,2,3,Albany City PD,2020-11-20,Albany,Albany,Other,Pointed Firearm,45.0000,Male,White,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,49.0000,Male,2020-11-20,Albany City PD,None,"Albany, Albany",Black,49.0000,Male,Pointed Firearm,None,3
75,3,4,Albany City PD,2020-12-08,Albany,Albany,Executing Arrest,Pointed Electronic Control Weapon,50.0000,Male,White,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,25.0000,Male,2020-12-08,Albany City PD,None,"Albany, Albany",Black,25.0000,Male,Pointed Electronic Control Weapon,None,4
100,4,5,Albany City PD,2021-01-11,Albany,Albany,Executing Arrest,Pointed Firearm,32.0000,Male,White,Non-Hispanic,Pointed Firearm,25.0000,Male,White,Unknown,Pointed Electronic Control Weapon,34.0000,Male,Asian,Unknown,Pointed Electronic Control Weapon,36.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,38.0000,Male,2021-01-11,Albany City PD,None,"Albany, Albany",Black,38.0000,Male,Pointed Firearm | Pointed Firearm | Pointed El...,None,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870825,34833,34834,New York City Police Department,2023-12-31,Brooklyn,Kings,"Medical, mental health, or welfare assistance",Used/Deployed Electronic Control Weapon,25.0000,Male,Asian,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,White,Non-Hispanic,33.0000,Male,2023-12-31,New York City Police Department,None,"Brooklyn, Kings",White,33.0000,Male,Used/Deployed Electronic Control Weapon,None,34834
870850,34834,34835,New York City Police Department,2023-12-31,Brooklyn,Kings,Response to unlawful or suspicious activity,Used/Deployed Electronic Control Weapon,32.0000,Male,Black,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Non-Hispanic,19.0000,Male,2023-12-31,New York City Police Department,None,"Brooklyn, Kings",Black,19.0000,Male,Used/Deployed Electronic Control Weapon,None,34835
870851,34834,34835,New York City Police Department,2023-12-31,Brooklyn,Kings,Response to unlawful or suspicious activity,Used/Deployed Electronic Control Weapon,32.0000,Male,Black,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,White,Hispanic,19.0000,Female,2023-12-31,New York City Police Department,None,"Brooklyn, Kings",White,19.0000,Female,Used/Deployed Electronic Control Weapon,None,34835
870875,34835,34836,New York City Police Department,2023-12-31,New York,New York,Response to unlawful or suspicious activity,Used/Deployed Electronic Control Weapon,35.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,White,Hispanic,43.0000,Male,2023-12-31,New York City Police Department,None,"New York, New York",White,43.0000,Male,Used/Deployed Electronic Control Weapon,None,34836
870900,34836,34837,New York City Police Department,2023-12-31,Queens,Queens,Other,Used/Deployed Electronic Control Weapon,23.0000,Male,Asian,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Hispanic,25.0000,Male,2023-12-31,New York City Police Department,None,"Queens, Queens",Black,25.0000,Male,Used/Deployed Electronic Control Weapon,None,34837

In [104]:
ny_uof_long = (
    ny_uof_long.assign(
        date = lambda x: x["NY_Incident Date"],
        agency_name = lambda x: x["NY_Agency Name"],
        ori = None,
        location = lambda x: x["NY_City/town/village (location Where Incident Occurred)"] + ", " + x["NY_County (location where incident occurred)"],
        subject_race = lambda x: x["NY_subject_race"],
        subject_age = lambda x: x["NY_subject_age"],
        subject_gender = lambda x: x["NY_subject_sex"],
        force_used = lambda x: x[ny_long_force_cols].apply(
            lambda row: ' | '.join([
                str(row[col]) for col in ny_long_force_cols 
                if (not pd.isna(row[col])) and (str(row[col]).strip() != "") and (str(row[col]).lower() != "nan" and str(row[col]) != "0")
            ]), axis=1
        ),
        indication_of_injury = None,
        incident_id = lambda x: x[["NY_Response ID\n(5/16/25 File)"]]
    )
)
ny_uof_long.head()

,NY_incident_id,NY_Response ID\n(5/16/25 File),NY_Agency Name,NY_Incident Date,NY_City/town/village (location Where Incident Occurred),NY_County (location where incident occurred),NY_Circumstance,NY_Officer 1 - Use of Force Type,NY_Officer 1 Age,NY_Officer 1 Sex,NY_Officer 1 Race,NY_Officer 1 Ethnicity,NY_Officer 2 - Use of Force Type,NY_Officer 2 Age,NY_Officer 2 Sex,NY_Officer 2 Race,NY_Officer 2 Ethnicity,NY_Officer 3 - Use of Force Type,NY_Officer 3 Age,NY_Officer 3 Sex,NY_Officer 3 Race,NY_Officer 3 Ethnicity,NY_Officer 4 - Use of Force Type,NY_Officer 4 Age,NY_Officer 4 Sex,NY_Officer 4 Race,NY_Officer 4 Ethnicity,NY_Officer 5 - Use of Force Type,NY_Officer 5 Age,NY_Officer 5 Sex,NY_Officer 5 Race,NY_Officer 5 Ethnicity,NY_Officer 6 - Use of Force Type,NY_Officer 6 Age,NY_Officer 6 Sex,NY_Officer 6 Race,NY_Officer 6 Ethnicity,NY_Officer 7 - Use of Force Type,NY_Officer 7 Age,NY_Officer 7 Sex,NY_Officer 7 Race,NY_Officer 7 Ethnicity,NY_Officer 8 - Use of Force Type,NY_Officer 8 Age,NY_Officer 8 Sex,NY_Officer 8 Race,NY_Officer 8 Ethnicity,NY_Officer 9 - Use of Force Type,NY_Officer 9 Age,NY_Officer 9 Sex,NY_Officer 9 Race,NY_Officer 9 Ethnicity,NY_Officer 10 - Use of Force Type,NY_Officer 10 Age,NY_Officer 10 Sex,NY_Officer 10 Race,NY_Officer 10 Ethnicity,NY_Officer 11 - Use of Force Type,NY_Officer 11 Age,NY_Officer 11 Sex,NY_Officer 11 Race,NY_Officer 11 Ethnicity,NY_Officer 12 - Use of Force Type,NY_Officer 12 Age,NY_Officer 12 Sex,NY_Officer 12 Race,NY_Officer 12 Ethnicity,NY_Officer 13 - Use of Force Type,NY_Officer 13 Age,NY_Officer 13 Sex,NY_Officer 13 Race,NY_Officer 13 Ethnicity,NY_Officer 14 - Use of Force Type,NY_Officer 14 Age,NY_Officer 14 Sex,NY_Officer 14 Race,NY_Officer 14 Ethnicity,NY_Officer 15 - Use of Force Type,NY_Officer 15 Age,NY_Officer 15 Sex,NY_Officer 15 Race,NY_Officer 15 Ethnicity,NY_Officer 16 - Use of Force Type,NY_Officer 16 Age,NY_Officer 16 Sex,NY_Officer 16 Race,NY_Officer 16 Ethnicity,NY_subject_number,NY_subject_race,NY_subject_ethnicity,NY_subject_age,NY_subject_sex,date,agency_name,ori,location,subject_race,subject_age,subject_gender,force_used,indication_of_injury,incident_id
0,0,1,Akron Vg PD,2020-12-22,Akron,Erie,Response to unlawful or suspicious activity,Pointed Firearm,27.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,White,Non-Hispanic,49.0000,Male,2020-12-22,Akron Vg PD,None,"Akron, Erie",White,49.0000,Male,Pointed Firearm,None,1
25,1,2,Albany City PD,2020-11-10,Albany,Albany,Other,Used/Deployed Chemical Agent,37.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,NaN,Male,2020-11-10,Albany City PD,None,"Albany, Albany",Black,NaN,Male,Used/Deployed Chemical Agent,None,2
50,2,3,Albany City PD,2020-11-20,Albany,Albany,Other,Pointed Firearm,45.0000,Male,White,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,49.0000,Male,2020-11-20,Albany City PD,None,"Albany, Albany",Black,49.0000,Male,Pointed Firearm,None,3
75,3,4,Albany City PD,2020-12-08,Albany,Albany,Executing Arrest,Pointed Electronic Control Weapon,50.0000,Male,White,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,25.0000,Male,2020-12-08,Albany City PD,None,"Albany, Albany",Black,25.0000,Male,Pointed Electronic Control Weapon,None,4
100,4,5,Albany City PD,2021-01-11,Albany,Albany,Executing Arrest,Pointed Firearm,32.0000,Male,White,Non-Hispanic,Pointed Firearm,25.0000,Male,White,Unknown,Pointed Electronic Control Weapon,34.0000,Male,Asian,Unknown,Pointed Electronic Control Weapon,36.0000,Male,White,Non-Hispanic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Black,Unknown,38.0000,Male,2021-01-11,Albany City PD,None,"Albany, Albany",Black,38.0000,Male,Pointed Firearm | Pointed Firearm | Pointed El...,None,5

### Cali

In [105]:
cali_df.head(1).T

                                                    0
DOJ_RECORD_ID                    W389724007L72FIA0IWQ
PERSON_NUMBER                                       1
AGENCY_ORI                                  CA0389700
AGENCY_NAME                       UC-SAN FRANCISCO PD
NON_REPORTING_AGENCY                                0
TIME_OF_STOP                                 10:25:00
DATE_OF_STOP                               2024-01-06
STOP_DURATION                                     110
LOC_CLOSEST_CITY                        SAN FRANCISCO
SCHOOL_CODE                                       NaN
SCHOOL_NAME                                       NaN
STOP_STUDENT                                        0
K12_SCHOOL_GROUNDS                                  0
RAE_FULL                                            2
G_FULL                                              1
SOR_STRAIGHT                                        1
AGE                                                50
AGE_GROUP                                           7
LIMITED_ENGLISH_FLUENCY                             0
PD_FULL                                             0
PERSON_UNHOUSED                                     1
PASSENGER_IN_VEHICLE                                0
INSIDE_RESIDENCE                                    0
WELFARE_WELLNESS_CHECK                              0
TOS_VEHICULAR                                       0
TOS_BICYCLE                                         0
TOS_PEDESTRIAN                                      1
CALL_FOR_SERVICE                                    0
REASON_FOR_STOP                                     2
RFS_TRAFFIC_VIOLATION_TYPE                        NaN
RFS_TRAFFIC_VIOLATION_CODE                        NaN
RFS_RS_OFF_WITNESS                             1.0000
RFS_RS_MATCH_SUSPECT                           0.0000
RFS_RS_WITNESS_ID                              0.0000
RFS_RS_CARRY_SUS_OBJECT                        0.0000
RFS_RS_ACTIONS_INDICATIVE                      0.0000
RFS_RS_SUSPECT_LOOK                            0.0000
RFS_RS_DRUG_TRANS                              0.0000
RFS_RS_VIOLENT_CRIME                           0.0000
RFS_RS_REASON_SUSP                             0.0000
RFS_RS_MATCH_VEHICLE                           0.0000
RFS_RS_CODE                                32111.0000
RFS_EC_DISCIPLINE_CODE                            NaN
RFS_EC_DISCIPLINE                                 NaN
RFS_PC_OFF_WITNESS                                NaN
RFS_PC_MATCH_SUSPECT                              NaN
RFS_PC_WITNESS_ID                                 NaN
RFS_PC_CARRY_SUS_OBJECT                           NaN
RFS_PC_ACTIONS_INDICATIVE                         NaN
RFS_PC_SUSPECT_LOOK                               NaN
RFS_PC_DRUG_TRANS                                 NaN
RFS_PC_VIOLENT_CRIME                              NaN
RFS_PC_REASON_SUSP                                NaN
RFS_PC_MATCH_VEHICLE                              NaN
RFS_PC_CODE                                       NaN
RFS_RG_TRAFFIC_MOVING                               0
RFS_RG_TRAFFIC_EQUIPMENT                            0
RFS_RG_TRAFFIC_NON_MOVING                           0
RFS_RG_OFF_WITNESS                                  1
RFS_RG_MATCH_SUSPECT                                0
RFS_RG_MATCH_VEHICLE                                0
RFS_RG_WITNESS_ID                                   0
RFS_RG_CARRY_SUS_OBJECT                             0
RFS_RG_ACTIONS_INDICATIVE                           0
RFS_RG_SUSPECT_LOOK                                 0
RFS_RG_DRUG_TRANS                                   0
RFS_RG_VIOLENT_CRIME                                0
RFS_RG_REASON_SUSP                                  0
RFS_RG_PROBABLE_CAUSE                               0
RFS_RG_WELFARE_AND_INST                             0
RFS_RG_KNOWN_PAROLE                                 0
RFS_RG_OUTSTANDING_WARRANT                          0
RFS_RG_TRUANT                                       0
RFS_RG_CONSENSUAL_SEARCH                            0
RFS_RG_DISCIPLINE                                   0
RFS_RG_SCHOOL_POLICY                                0
RFS_RG_NOT_COMMUNICATED                             0
NFA_WRITTEN_STATEMENT                          0.0000
NFA_ASKED_SEARCH_PER                           0.0000
NFA_ASKED_SEARCH_PROP                          0.0000
NFA_ASKED_ID_PASSENGER                         0.0000
NFA_ASKED_PAROLE                               0.0000
NFA_CURB_DETENT                                0.0000
NFA_SOBRIETY_TEST                              0.0000
NFA_PATCAR_DETENT                              0.0000
NFA_CANINE_SEARCH                              0.0000
NFA_PHOTO                                      1.0000
NFA_REMOVED_VEHICLE_ORDER                      0.0000
NFA_PROP_SEIZE                                 0.0000
NFA_RAN_NAME_PASSENGER                         0.0000
NFA_SEARCH_PERSON                              1.0000
NFA_SEARCH_PROPERTY                            1.0000
NFA_TERRY_FRISK                                1.0000
NFA_VEHICLE_IMPOUND                            0.0000
NFA_NONE                                       0.0000
NFA_SEARCH_PERS_CONSENT                           NaN
NFA_SEARCH_PROP_CONSENT                           NaN
OFA_HANDCUFFED                                 1.0000
OFA_BATON_DRAWN                                0.0000
OFA_BATON_USED                                 0.0000
OFA_CHEM_SPRAY                                 0.0000
OFA_ELECT_DEVICE_POINT                         0.0000
OFA_ELECT_DEVICE_STUN                          0.0000
OFA_ELECT_DEVICE_DART                          0.0000
OFA_FIREARM_UNHOLSTERED                        0.0000
OFA_FIREARM_POINT                              0.0000
OFA_FIREARM_DISCHARGE                          0.0000
OFA_IMPACT_PROJECTILE_POINT                    0.0000
OFA_IMPACT_PROJECTILE_DISCHARGE                0.0000
OFA_CANINE_COMPLIANCE                          0.0000
OFA_CANINE_BITE                                0.0000
OFA_REMOVED_VEHICLE_PHYCONTACT                 0.0000
OFA_PHYSICAL_COMPLIANCE                        0.0000
OFA_USE_VEHICLE                                0.0000
OFA_NONE                                       0.0000
BFS_OFFICER_SAFETY                             0.0000
BFS_SEARCH_WARRANT                             0.0000
BFS_PAROLE                                     0.0000
BFS_SUSPECT_WEAPON                             0.0000
BFS_VISIBLE_CONTRABAND                         0.0000
BFS_ODOR_CONTRABAND                            0.0000
BFS_CANINE_DETECT                              0.0000
BFS_EVIDENCE                                   0.0000
BFS_INCIDENT                                   1.0000
BFS_EXIGENT_CIRCUM                             0.0000
BFS_VEHICLE_INVENT                             0.0000
BFS_SCHOOL_POLICY                              0.0000
BFS_CONSENT_GIVEN                              0.0000
CTP_VERBAL                                          0
CTP_WRITTEN                                         0
CTP_IMPLIED                                         0
CED_NONE_CONTRABAND                                 1
CED_FIREARM                                         0
CED_AMMUNITION                                      0
CED_WEAPON                                          0
CED_DRUGS                                           0
CED_ALCOHOL                                         0
CED_MONEY                                           0
CED_DRUG_PARAPHERNALIA                              0
CED_STOLEN_PROP                                     0
CED_ELECT_DEVICE                                    0
CED_OTHER_CONTRABAND                                0
BPS_SAFEKEEPING                                   NaN
BPS_CONTRABAND                                    NaN
BPS_EVIDENCE                                      NaN
BPS_IMPOUND_VEHICLE                               NaN
BPS_ABANDON_PROP                                  NaN
BPS_VIOLATE_SCHOOL                                NaN
TPS_FIREARM                                       NaN
TPS_AMMUNITION                                    NaN
TPS_WEAPON                                        NaN
TPS_DRUGS                                         NaN
TPS_ALCOHOL                                       NaN
TPS_MONEY                                         NaN
TPS_DRUG_PARAPHERNALIA                            NaN
TPS_STOLEN_PROP                                   NaN
TPS_CELLPHONE                                     NaN
TPS_VEHICLE                                       NaN
TPS_CONTRABAND                                    NaN
ROS_NO_ACTION                                  0.0000
ROS_CITATION                                   0.0000
ROS_IN_FIELD_CITE_RELEASE                      0.0000
ROS_CUSTODIAL_WARRANT                          1.0000
ROS_CUSTODIAL_WITHOUT_WARRANT                  0.0000
ROS_FIELD_INTERVIEW_CARD                       0.0000
ROS_NONCRIMINAL_TRANSPORT                      0.0000
ROS_CONTACT_LEGAL_GUARDIAN                     0.0000
ROS_PSYCH_HOLD                                 0.0000
ROS_US_HOMELAND                                0.0000
ROS_REFERRAL_SCHOOL_ADMIN                      0.0000
ROS_REFERRAL_SCHOOL_COUNSELOR                  0.0000
ROS_WRITTEN_WARNING                            0.0000
ROS_VERBAL_WARNING                             0.0000
ROS_CITATION_CDS                                  NaN
ROS_IN_FIELD_CITE_RELEASE_CDS                     NaN
ROS_CUSTODIAL_WOUT_WARRANT_CDS                    NaN
ROS_VERBAL_WARNING_CDS                            NaN
ROS_WRITTEN_WARNING_CDS                           NaN
county_name                            San Francisco

In [106]:
(cali_df[["OFA_FIREARM_UNHOLSTERED", "OFA_FIREARM_POINT", "OFA_FIREARM_DISCHARGE"]] != 0).any(axis=1).sum()

np.int64(31444)

In [107]:
(cali_df[["OFA_FIREARM_DISCHARGE"]] != 0).any(axis=1).sum()

np.int64(1401)

In [108]:
cali_force_cols = [
                    c for c in cali_df.columns if "OFA_" in c 
                                        and (c != "OFA_NONE") 
                                        and (c != "OFA_HANDCUFFED")
                                        and (c != "OFA_BATON_DRAWN")
                                        and (c != "OFA_ELECT_DEVICE_POINT")
                                        and (c != "OFA_FIREARM_UNHOLSTERED")
                                        and (c != "OFA_FIREARM_POINT")
                                        and (c != "OFA_IMPACT_PROJECTILE_POINT")
                                        and (c != "OFA_CANINE_COMPLIANCE")
                  ]
cali_force_cols

['OFA_BATON_USED',
 'OFA_CHEM_SPRAY',
 'OFA_ELECT_DEVICE_STUN',
 'OFA_ELECT_DEVICE_DART',
 'OFA_FIREARM_DISCHARGE',
 'OFA_IMPACT_PROJECTILE_DISCHARGE',
 'OFA_CANINE_BITE',
 'OFA_REMOVED_VEHICLE_PHYCONTACT',
 'OFA_PHYSICAL_COMPLIANCE',
 'OFA_USE_VEHICLE']

In [109]:
cali_df[cali_force_cols].info()

<class 'pandas.DataFrame'>
RangeIndex: 5065428 entries, 0 to 5065427
Data columns (total 10 columns):
 #   Column                           Dtype
---  ------                           -----
 0   OFA_BATON_USED                   float32
 1   OFA_CHEM_SPRAY                   float32
 2   OFA_ELECT_DEVICE_STUN            float32
 3   OFA_ELECT_DEVICE_DART            float32
 4   OFA_FIREARM_DISCHARGE            float32
 5   OFA_IMPACT_PROJECTILE_DISCHARGE  float32
 6   OFA_CANINE_BITE                  float32
 7   OFA_REMOVED_VEHICLE_PHYCONTACT   float32
 8   OFA_PHYSICAL_COMPLIANCE          float32
 9   OFA_USE_VEHICLE                  float32
dtypes: float32(10)
memory usage: 193.2 MB

In [110]:
cali_df[cali_force_cols] = cali_df[cali_force_cols].fillna(0)

In [111]:
cali_df[cali_force_cols] = cali_df[cali_force_cols].astype(int)

In [112]:
cali_force_df = (
    cali_df[
        (cali_df[cali_force_cols] != 0).any(axis=1)
    ]
)
print(cali_force_df.shape)
cali_force_df.head()

(36375, 179)

,DOJ_RECORD_ID,PERSON_NUMBER,AGENCY_ORI,AGENCY_NAME,NON_REPORTING_AGENCY,TIME_OF_STOP,DATE_OF_STOP,STOP_DURATION,LOC_CLOSEST_CITY,SCHOOL_CODE,SCHOOL_NAME,STOP_STUDENT,K12_SCHOOL_GROUNDS,RAE_FULL,G_FULL,SOR_STRAIGHT,AGE,AGE_GROUP,LIMITED_ENGLISH_FLUENCY,PD_FULL,PERSON_UNHOUSED,PASSENGER_IN_VEHICLE,INSIDE_RESIDENCE,WELFARE_WELLNESS_CHECK,TOS_VEHICULAR,TOS_BICYCLE,TOS_PEDESTRIAN,CALL_FOR_SERVICE,REASON_FOR_STOP,RFS_TRAFFIC_VIOLATION_TYPE,RFS_TRAFFIC_VIOLATION_CODE,RFS_RS_OFF_WITNESS,RFS_RS_MATCH_SUSPECT,RFS_RS_WITNESS_ID,RFS_RS_CARRY_SUS_OBJECT,RFS_RS_ACTIONS_INDICATIVE,RFS_RS_SUSPECT_LOOK,RFS_RS_DRUG_TRANS,RFS_RS_VIOLENT_CRIME,RFS_RS_REASON_SUSP,RFS_RS_MATCH_VEHICLE,RFS_RS_CODE,RFS_EC_DISCIPLINE_CODE,RFS_EC_DISCIPLINE,RFS_PC_OFF_WITNESS,RFS_PC_MATCH_SUSPECT,RFS_PC_WITNESS_ID,RFS_PC_CARRY_SUS_OBJECT,RFS_PC_ACTIONS_INDICATIVE,RFS_PC_SUSPECT_LOOK,RFS_PC_DRUG_TRANS,RFS_PC_VIOLENT_CRIME,RFS_PC_REASON_SUSP,RFS_PC_MATCH_VEHICLE,RFS_PC_CODE,RFS_RG_TRAFFIC_MOVING,RFS_RG_TRAFFIC_EQUIPMENT,RFS_RG_TRAFFIC_NON_MOVING,RFS_RG_OFF_WITNESS,RFS_RG_MATCH_SUSPECT,RFS_RG_MATCH_VEHICLE,RFS_RG_WITNESS_ID,RFS_RG_CARRY_SUS_OBJECT,RFS_RG_ACTIONS_INDICATIVE,RFS_RG_SUSPECT_LOOK,RFS_RG_DRUG_TRANS,RFS_RG_VIOLENT_CRIME,RFS_RG_REASON_SUSP,RFS_RG_PROBABLE_CAUSE,RFS_RG_WELFARE_AND_INST,RFS_RG_KNOWN_PAROLE,RFS_RG_OUTSTANDING_WARRANT,RFS_RG_TRUANT,RFS_RG_CONSENSUAL_SEARCH,RFS_RG_DISCIPLINE,RFS_RG_SCHOOL_POLICY,RFS_RG_NOT_COMMUNICATED,NFA_WRITTEN_STATEMENT,NFA_ASKED_SEARCH_PER,NFA_ASKED_SEARCH_PROP,NFA_ASKED_ID_PASSENGER,NFA_ASKED_PAROLE,NFA_CURB_DETENT,NFA_SOBRIETY_TEST,NFA_PATCAR_DETENT,NFA_CANINE_SEARCH,NFA_PHOTO,NFA_REMOVED_VEHICLE_ORDER,NFA_PROP_SEIZE,NFA_RAN_NAME_PASSENGER,NFA_SEARCH_PERSON,NFA_SEARCH_PROPERTY,NFA_TERRY_FRISK,NFA_VEHICLE_IMPOUND,NFA_NONE,NFA_SEARCH_PERS_CONSENT,NFA_SEARCH_PROP_CONSENT,OFA_HANDCUFFED,OFA_BATON_DRAWN,OFA_BATON_USED,OFA_CHEM_SPRAY,OFA_ELECT_DEVICE_POINT,OFA_ELECT_DEVICE_STUN,OFA_ELECT_DEVICE_DART,OFA_FIREARM_UNHOLSTERED,OFA_FIREARM_POINT,OFA_FIREARM_DISCHARGE,OFA_IMPACT_PROJECTILE_POINT,OFA_IMPACT_PROJECTILE_DISCHARGE,OFA_CANINE_COMPLIANCE,OFA_CANINE_BITE,OFA_REMOVED_VEHICLE_PHYCONTACT,OFA_PHYSICAL_COMPLIANCE,OFA_USE_VEHICLE,OFA_NONE,BFS_OFFICER_SAFETY,BFS_SEARCH_WARRANT,BFS_PAROLE,BFS_SUSPECT_WEAPON,BFS_VISIBLE_CONTRABAND,BFS_ODOR_CONTRABAND,BFS_CANINE_DETECT,BFS_EVIDENCE,BFS_INCIDENT,BFS_EXIGENT_CIRCUM,BFS_VEHICLE_INVENT,BFS_SCHOOL_POLICY,BFS_CONSENT_GIVEN,CTP_VERBAL,CTP_WRITTEN,CTP_IMPLIED,CED_NONE_CONTRABAND,CED_FIREARM,CED_AMMUNITION,CED_WEAPON,CED_DRUGS,CED_ALCOHOL,CED_MONEY,CED_DRUG_PARAPHERNALIA,CED_STOLEN_PROP,CED_ELECT_DEVICE,CED_OTHER_CONTRABAND,BPS_SAFEKEEPING,BPS_CONTRABAND,BPS_EVIDENCE,BPS_IMPOUND_VEHICLE,BPS_ABANDON_PROP,BPS_VIOLATE_SCHOOL,TPS_FIREARM,TPS_AMMUNITION,TPS_WEAPON,TPS_DRUGS,TPS_ALCOHOL,TPS_MONEY,TPS_DRUG_PARAPHERNALIA,TPS_STOLEN_PROP,TPS_CELLPHONE,TPS_VEHICLE,TPS_CONTRABAND,ROS_NO_ACTION,ROS_CITATION,ROS_IN_FIELD_CITE_RELEASE,ROS_CUSTODIAL_WARRANT,ROS_CUSTODIAL_WITHOUT_WARRANT,ROS_FIELD_INTERVIEW_CARD,ROS_NONCRIMINAL_TRANSPORT,ROS_CONTACT_LEGAL_GUARDIAN,ROS_PSYCH_HOLD,ROS_US_HOMELAND,ROS_REFERRAL_SCHOOL_ADMIN,ROS_REFERRAL_SCHOOL_COUNSELOR,ROS_WRITTEN_WARNING,ROS_VERBAL_WARNING,ROS_CITATION_CDS,ROS_IN_FIELD_CITE_RELEASE_CDS,ROS_CUSTODIAL_WOUT_WARRANT_CDS,ROS_VERBAL_WARNING_CDS,ROS_WRITTEN_WARNING_CDS,county_name
51,U3800240116626931439,1,CA0380000,SAN FRANCISCO CO SO,0,17:02:00,2024-01-11,20,SAN FRANCISCO,NaN,NaN,0,0,2,1,1,35,6,0,0,0,0,0,0,0,0,1,0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,1.0000,0.0000,0,0,0.0000,0,0,0.0000,0.0000,0,0.0000,0,0.0000,0,1,1,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN,NaN,NaN,San Francisco
256,W389724067GDGOAZ18E9,1,CA0389700,UC-SAN FRANCISCO PD,0,09:58:00,2024-03-04,329,SAN FRANCISCO,NaN,NaN,0,0,2,1,1,30,5,0,0,0,0,0,0,0,0,1,1,2,NaN,NaN,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,23132.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,1.0000,0.0000,0,0,0.0000,0,0,0.0000,0.0000,0,0.0000,0,0.0000,0,0,1,0,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,"23132, 48122, 50126",NaN,NaN,San Francisco
283,U3800240793C646E114C,1,CA0380000,SAN FRANCISCO CO SO,1,14:44:00,2024-03-19,16,SAN FRANCISCO,NaN,NaN,0,0,2,1,1,40,6,0,0,0,0,0,0,0,0,1,1,2,NaN,NaN,1.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,32080.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,NaN,NaN,1.0000,0.0000,0,0,0.0000,0,0,0.0000,0.0000,0,0.0000,0,0.0000,0,0,1,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,13081,NaN,NaN,San Francisco
325,W389724063BZ8GXQ3479,1,CA0389700,UC-SAN FRANCISCO PD,0,23:08:00,2024-02-23,37,SAN FRANCISCO,NaN,NaN,0,0,2,1,1,30,5,0,0,0,0,0,0,1,0,0,0,1,2.0000,66979.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,0.0000,0.0000,0,0,0.0000,0,0,0.0000,0.0000,0,0.0000,0,0.0000,0,1,0,0,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,1.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,66979,42127,NaN,NaN,NaN,San Francisco
332,U3800240887D7A01BEDA,1,CA0380000,SAN FRANCISCO CO SO,0,06:10:00,2024-03-28,30,SAN FRANCISCO,NaN,NaN,0,0,7,1,1,50,7,0,0,1,0,0,0,0,0,1,1,2,NaN,NaN,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,32080.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,1.0000,0.0000,0,0,0.0000,0,0,0.0000,0.0000,0,0.0000,0,0.0000,0,0,1,0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0,0,0,1,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,32080,NaN,NaN,San Francisco

In [113]:
cali_cols_to_keep = [
    "DOJ_RECORD_ID",
    "AGENCY_ORI", "AGENCY_NAME", 
    "DATE_OF_STOP",
    "county_name", "LOC_CLOSEST_CITY", 
    "RAE_FULL", "G_FULL", "SOR_STRAIGHT", "PD_FULL", "LIMITED_ENGLISH_FLUENCY", "AGE", 
    "REASON_FOR_STOP",
    "OFA_NONE"
]
cali_cols_to_keep += cali_force_cols

In [114]:
cali_force_df = cali_force_df[cali_cols_to_keep]

In [115]:
cali_force_df.head()

,DOJ_RECORD_ID,AGENCY_ORI,AGENCY_NAME,DATE_OF_STOP,county_name,LOC_CLOSEST_CITY,RAE_FULL,G_FULL,SOR_STRAIGHT,PD_FULL,LIMITED_ENGLISH_FLUENCY,AGE,REASON_FOR_STOP,OFA_NONE,OFA_BATON_USED,OFA_CHEM_SPRAY,OFA_ELECT_DEVICE_STUN,OFA_ELECT_DEVICE_DART,OFA_FIREARM_DISCHARGE,OFA_IMPACT_PROJECTILE_DISCHARGE,OFA_CANINE_BITE,OFA_REMOVED_VEHICLE_PHYCONTACT,OFA_PHYSICAL_COMPLIANCE,OFA_USE_VEHICLE
51,U3800240116626931439,CA0380000,SAN FRANCISCO CO SO,2024-01-11,San Francisco,SAN FRANCISCO,2,1,1,0,0,35,4,0.0000,0,0,0,0,0,0,0,1,1,0
256,W389724067GDGOAZ18E9,CA0389700,UC-SAN FRANCISCO PD,2024-03-04,San Francisco,SAN FRANCISCO,2,1,1,0,0,30,2,0.0000,0,0,0,0,0,0,0,0,1,0
283,U3800240793C646E114C,CA0380000,SAN FRANCISCO CO SO,2024-03-19,San Francisco,SAN FRANCISCO,2,1,1,0,0,40,2,0.0000,0,0,0,0,0,0,0,0,1,0
325,W389724063BZ8GXQ3479,CA0389700,UC-SAN FRANCISCO PD,2024-02-23,San Francisco,SAN FRANCISCO,2,1,1,0,0,30,1,0.0000,0,0,0,0,0,0,0,1,0,0
332,U3800240887D7A01BEDA,CA0380000,SAN FRANCISCO CO SO,2024-03-28,San Francisco,SAN FRANCISCO,7,1,1,0,0,50,2,0.0000,0,0,0,0,0,0,0,0,1,0

In [116]:
cali_force_df = cali_force_df.add_prefix("CALI_")

In [117]:
cali_force_cols = ["CALI_" + c for c in cali_force_cols]

In [118]:
cali_race_dict = {
    1: "Asian",
    2: "Black",
    3: "Hispanic",
    4: "Middle Eastern",
    5: "Native American",
    6: "Pacific Islander",
    7: "White",
    8: "Multiracial"
}

cali_gender_dict = {
    1: "Male",
    2: "Female",
    3: "Trans Male",
    4: "Trans Female",
    5: "Nonbinary"
}

In [119]:
cali_force_df = (
    cali_force_df.assign(
        date = lambda x: x["CALI_DATE_OF_STOP"],
        agency_name = lambda x: x["CALI_AGENCY_NAME"],
        ori = lambda x: x["CALI_AGENCY_ORI"],
        location = lambda x: x["CALI_county_name"],
        subject_race = lambda x: x["CALI_RAE_FULL"].map(cali_race_dict),
        subject_age = lambda x: x["CALI_AGE"],
        subject_gender = lambda x: x["CALI_G_FULL"].map(cali_gender_dict),
        force_used = lambda x: x[cali_force_cols].apply(
            lambda row: ' | '.join([col for col in cali_force_cols if row[col] == 1]), axis=1
        ),
        indication_of_injury = "",
        incident_id = lambda x: x[["CALI_DOJ_RECORD_ID"]].apply(
                lambda row: [str(v) for v in row if pd.notna(v)],
                axis=1
            ))
)
cali_force_df.head()

,CALI_DOJ_RECORD_ID,CALI_AGENCY_ORI,CALI_AGENCY_NAME,CALI_DATE_OF_STOP,CALI_county_name,CALI_LOC_CLOSEST_CITY,CALI_RAE_FULL,CALI_G_FULL,CALI_SOR_STRAIGHT,CALI_PD_FULL,CALI_LIMITED_ENGLISH_FLUENCY,CALI_AGE,CALI_REASON_FOR_STOP,CALI_OFA_NONE,CALI_OFA_BATON_USED,CALI_OFA_CHEM_SPRAY,CALI_OFA_ELECT_DEVICE_STUN,CALI_OFA_ELECT_DEVICE_DART,CALI_OFA_FIREARM_DISCHARGE,CALI_OFA_IMPACT_PROJECTILE_DISCHARGE,CALI_OFA_CANINE_BITE,CALI_OFA_REMOVED_VEHICLE_PHYCONTACT,CALI_OFA_PHYSICAL_COMPLIANCE,CALI_OFA_USE_VEHICLE,date,agency_name,ori,location,subject_race,subject_age,subject_gender,force_used,indication_of_injury,incident_id
51,U3800240116626931439,CA0380000,SAN FRANCISCO CO SO,2024-01-11,San Francisco,SAN FRANCISCO,2,1,1,0,0,35,4,0.0000,0,0,0,0,0,0,0,1,1,0,2024-01-11,SAN FRANCISCO CO SO,CA0380000,San Francisco,Black,35,Male,CALI_OFA_REMOVED_VEHICLE_PHYCONTACT | CALI_OFA...,,[U3800240116626931439]
256,W389724067GDGOAZ18E9,CA0389700,UC-SAN FRANCISCO PD,2024-03-04,San Francisco,SAN FRANCISCO,2,1,1,0,0,30,2,0.0000,0,0,0,0,0,0,0,0,1,0,2024-03-04,UC-SAN FRANCISCO PD,CA0389700,San Francisco,Black,30,Male,CALI_OFA_PHYSICAL_COMPLIANCE,,[W389724067GDGOAZ18E9]
283,U3800240793C646E114C,CA0380000,SAN FRANCISCO CO SO,2024-03-19,San Francisco,SAN FRANCISCO,2,1,1,0,0,40,2,0.0000,0,0,0,0,0,0,0,0,1,0,2024-03-19,SAN FRANCISCO CO SO,CA0380000,San Francisco,Black,40,Male,CALI_OFA_PHYSICAL_COMPLIANCE,,[U3800240793C646E114C]
325,W389724063BZ8GXQ3479,CA0389700,UC-SAN FRANCISCO PD,2024-02-23,San Francisco,SAN FRANCISCO,2,1,1,0,0,30,1,0.0000,0,0,0,0,0,0,0,1,0,0,2024-02-23,UC-SAN FRANCISCO PD,CA0389700,San Francisco,Black,30,Male,CALI_OFA_REMOVED_VEHICLE_PHYCONTACT,,[W389724063BZ8GXQ3479]
332,U3800240887D7A01BEDA,CA0380000,SAN FRANCISCO CO SO,2024-03-28,San Francisco,SAN FRANCISCO,7,1,1,0,0,50,2,0.0000,0,0,0,0,0,0,0,0,1,0,2024-03-28,SAN FRANCISCO CO SO,CA0380000,San Francisco,White,50,Male,CALI_OFA_PHYSICAL_COMPLIANCE,,[U3800240887D7A01BEDA]

In [120]:
cali_force_df.info()

<class 'pandas.DataFrame'>
Index: 36375 entries, 51 to 5065417
Data columns (total 34 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   CALI_DOJ_RECORD_ID                    36375 non-null  str
 1   CALI_AGENCY_ORI                       36375 non-null  str
 2   CALI_AGENCY_NAME                      36375 non-null  str
 3   CALI_DATE_OF_STOP                     36375 non-null  str
 4   CALI_county_name                      36375 non-null  str
 5   CALI_LOC_CLOSEST_CITY                 36375 non-null  str
 6   CALI_RAE_FULL                         36375 non-null  int8
 7   CALI_G_FULL                           36375 non-null  int8
 8   CALI_SOR_STRAIGHT                     36375 non-null  int8
 9   CALI_PD_FULL                          36375 non-null  int8
 10  CALI_LIMITED_ENGLISH_FLUENCY          36375 non-null  int8
 11  CALI_AGE                              36375 non-null  int8
 12  CALI_REASON_FOR_STOP                  36375 non-null  int8
 13  CALI_OFA_NONE                         36375 non-null  float32
 14  CALI_OFA_BATON_USED                   36375 non-null  int64
 15  CALI_OFA_CHEM_SPRAY                   36375 non-null  int64
 16  CALI_OFA_ELECT_DEVICE_STUN            36375 non-null  int64
 17  CALI_OFA_ELECT_DEVICE_DART            36375 non-null  int64
 18  CALI_OFA_FIREARM_DISCHARGE            36375 non-null  int64
 19  CALI_OFA_IMPACT_PROJECTILE_DISCHARGE  36375 non-null  int64
 20  CALI_OFA_CANINE_BITE                  36375 non-null  int64
 21  CALI_OFA_REMOVED_VEHICLE_PHYCONTACT   36375 non-null  int64
 22  CALI_OFA_PHYSICAL_COMPLIANCE          36375 non-null  int64
 23  CALI_OFA_USE_VEHICLE                  36375 non-null  int64
 24  date                                  36375 non-null  str
 25  agency_name                           36375 non-null  str
 26  ori                                   36375 non-null  str
 27  location                              36375 non-null  str
 28  subject_race                          36375 non-null  str
 29  subject_age                           36375 non-null  int8
 30  subject_gender                        36375 non-null  str
 31  force_used                            36375 non-null  str
 32  indication_of_injury                  36375 non-null  str
 33  incident_id                           36375 non-null  object
dtypes: float32(1), int64(10), int8(8), object(1), str(14)
memory usage: 7.6+ MB

## Concating

In [121]:
# Add a 'state' column to each dataframe before concatenation
nj_df_with_state = nj_df.copy()
nj_df_with_state["state"] = "NJ"

ohio_df_with_state = ohio_df.copy()
ohio_df_with_state["state"] = "OH"

ny_df_with_state = ny_df.copy()
ny_df_with_state["state"] = "NY"

ny_uof_long_with_state = ny_uof_long.copy()
ny_uof_long_with_state["state"] = "NY"

cali_force_df_with_state = cali_force_df.copy()
cali_force_df_with_state["state"] = "CA"

incidents_df = pd.concat([
    nj_df_with_state,
    ohio_df_with_state,
    ny_df_with_state,
    ny_uof_long_with_state,
    cali_force_df_with_state
])

incidents_df = incidents_df[[col for col in standard_cols if col in incidents_df.columns] +
                            [col for col in incidents_df.columns if col not in standard_cols]]
incidents_df.head()

,date,agency_name,ori,state,location,subject_race,subject_age,subject_gender,force_used,indication_of_injury,incident_id,NJ_Form ID,NJ_County,NJ_Agency Name,NJ_Incident ID,NJ_Report Number,NJ_Incident Case Number,NJ_Incident Date,NJ_Incident Type,NJ_Subject Actions,NJ_Subject Resistance,NJ_Subject Medical Treatment,NJ_Subject Injury Type,NJ_Subject Arrested,NJ_Reason Subject Not Arrested,NJ_Subject Type,NJ_Subject Age,NJ_Subject Race/Ethnicity,NJ_Subject Gender,NJ_Force Type,Ohio_AgencyName,Ohio_IncidentNumber,Ohio_IncidentDate,Ohio_InitialContactCircumstances,Ohio_LocationType,Ohio_SubjectResistanceTypes,Ohio_SubjectArmed/BelievedToBeArmed,Ohio_SubjectRaceEthnicity,Ohio_SubjectGender,Ohio_SubjectInjuries,Ohio_SubjectImpairments,Ohio_OfficerType,Ohio_OfficerResponse/ForceTypes,Ohio_OfficerRaceEthnicity,Ohio_OfficerGender,Ohio_OfficerInjuries,NY_TRI Incident Number,NY_ForceType,NY_Occurrence Date,NY_Incident Pct,NY_Patrol Borough,NY_YearMonthShort,NY_BasisForEncounter,NY_Subject Injury Level,NY_Subject Injured,NY_Age,NY_Subject Race,NY_Subject Gender,NY_Force Against MOS,NY_Subject Used Force,NY_incident_id,NY_Response ID\n(5/16/25 File),NY_Agency Name,NY_Incident Date,NY_City/town/village (location Where Incident Occurred),NY_County (location where incident occurred),NY_Circumstance,NY_Officer 1 - Use of Force Type,NY_Officer 1 Age,NY_Officer 1 Sex,NY_Officer 1 Race,NY_Officer 1 Ethnicity,NY_Officer 2 - Use of Force Type,NY_Officer 2 Age,NY_Officer 2 Sex,NY_Officer 2 Race,NY_Officer 2 Ethnicity,NY_Officer 3 - Use of Force Type,NY_Officer 3 Age,NY_Officer 3 Sex,NY_Officer 3 Race,NY_Officer 3 Ethnicity,NY_Officer 4 - Use of Force Type,NY_Officer 4 Age,NY_Officer 4 Sex,NY_Officer 4 Race,NY_Officer 4 Ethnicity,NY_Officer 5 - Use of Force Type,NY_Officer 5 Age,NY_Officer 5 Sex,NY_Officer 5 Race,NY_Officer 5 Ethnicity,NY_Officer 6 - Use of Force Type,NY_Officer 6 Age,NY_Officer 6 Sex,NY_Officer 6 Race,NY_Officer 6 Ethnicity,NY_Officer 7 - Use of Force Type,NY_Officer 7 Age,NY_Officer 7 Sex,NY_Officer 7 Race,NY_Officer 7 Ethnicity,NY_Officer 8 - Use of Force Type,NY_Officer 8 Age,NY_Officer 8 Sex,NY_Officer 8 Race,NY_Officer 8 Ethnicity,NY_Officer 9 - Use of Force Type,NY_Officer 9 Age,NY_Officer 9 Sex,NY_Officer 9 Race,NY_Officer 9 Ethnicity,NY_Officer 10 - Use of Force Type,NY_Officer 10 Age,NY_Officer 10 Sex,NY_Officer 10 Race,NY_Officer 10 Ethnicity,NY_Officer 11 - Use of Force Type,NY_Officer 11 Age,NY_Officer 11 Sex,NY_Officer 11 Race,NY_Officer 11 Ethnicity,NY_Officer 12 - Use of Force Type,NY_Officer 12 Age,NY_Officer 12 Sex,NY_Officer 12 Race,NY_Officer 12 Ethnicity,NY_Officer 13 - Use of Force Type,NY_Officer 13 Age,NY_Officer 13 Sex,NY_Officer 13 Race,NY_Officer 13 Ethnicity,NY_Officer 14 - Use of Force Type,NY_Officer 14 Age,NY_Officer 14 Sex,NY_Officer 14 Race,NY_Officer 14 Ethnicity,NY_Officer 15 - Use of Force Type,NY_Officer 15 Age,NY_Officer 15 Sex,NY_Officer 15 Race,NY_Officer 15 Ethnicity,NY_Officer 16 - Use of Force Type,NY_Officer 16 Age,NY_Officer 16 Sex,NY_Officer 16 Race,NY_Officer 16 Ethnicity,NY_subject_number,NY_subject_race,NY_subject_ethnicity,NY_subject_age,NY_subject_sex,CALI_DOJ_RECORD_ID,CALI_AGENCY_ORI,CALI_AGENCY_NAME,CALI_DATE_OF_STOP,CALI_county_name,CALI_LOC_CLOSEST_CITY,CALI_RAE_FULL,CALI_G_FULL,CALI_SOR_STRAIGHT,CALI_PD_FULL,CALI_LIMITED_ENGLISH_FLUENCY,CALI_AGE,CALI_REASON_FOR_STOP,CALI_OFA_NONE,CALI_OFA_BATON_USED,CALI_OFA_CHEM_SPRAY,CALI_OFA_ELECT_DEVICE_STUN,CALI_OFA_ELECT_DEVICE_DART,CALI_OFA_FIREARM_DISCHARGE,CALI_OFA_IMPACT_PROJECTILE_DISCHARGE,CALI_OFA_CANINE_BITE,CALI_OFA_REMOVED_VEHICLE_PHYCONTACT,CALI_OFA_PHYSICAL_COMPLIANCE,CALI_OFA_USE_VEHICLE
0,11/6/2023,Berkeley Twp PD,None,NJ,Ocean,Hispanic,28,Male,Used take down on,None,"[OCEAN-BERKELEY TWP PD-23-003647, UOF23-11-52,...",866515.0000,Ocean,Berkeley Twp PD,OCEAN-BERKELEY TWP PD-23-003647,UOF23-11-52,23-003647,11/6/2023,Assault,Attempt to escape from Custody,Passive Resistor,NaN,NaN,TRUE,NaN,Person,28,Hispanic,Male,Used take down on,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5/13/2021,Toms River Twp PD,None,NJ,Ocean,White,55,Female,Used arms,None,"[OCEAN-TOMS RIVER TWP PD-21-20078, UOF21-5-48,...",91681.0000,Ocean,Toms River Twp PD,OCEAN-TOMS RIVER TWP PD-21-20078,UOF21-5-48,21-20078,5/13/2021,"Welfare Check, Potential Mental Health Incident","Resisted arrest/police officer control, Verbal...","Verbal, Resistive tension (stiffening, tigheni...",NaN,NaN,FALSE,Medical/Mental Health Incident,Person,55,White,Female,Used arms,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/27/2021,Vineland PD,None,NJ,Cumberland,Hispanic,37,Male,Canine bit (apprehension),None,"[CUMBERLAND-VINELAND PD-2021-4288, UOF21-1-19,...",50307.0000,Cumberland,Vineland PD,CUMBERLAND-VINELAND PD-2021-4288,UOF21-1-19,2021-4288,1/27/2021,MV/Traffic Stop,"Resisted arrest/police officer control, Attack...","Resistive tension (stiffening, tighening muscl...","EMS on scene, Hospital",Abrasion/Laceration/Puncture,TRUE,NaN,Person,37,Hispanic,Male,Canine bit (apprehension),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/8/2022,Lakewood PD,None,NJ,Ocean,Hispanic,35,Female,Used arms/hands,None,"[OCEAN-LAKEWOOD PD-22-001779, UOF22-1-9, 22-00...",201634.0000,Ocean,Lakewood PD,OCEAN-LAKEWOOD PD-22-001779,UOF22-1-9,22-001779,1/8/2022,Medical Emergency,"Strike with open hand, fist, or elbow",Active Resistor,NaN,NaN,FALSE,Medical/Mental Health Incident,Person,35,Hispanic,Female,Used arms/hands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5/11/2025,Rutherford PD,None,NJ,Bergen,Hispanic,19,Male,Used take down on,None,"[BERGEN-RUTHERFORD PD-25-08463, UOF25-5-1, 25-...",1594362.0000,Bergen,Rutherford PD,BERGEN-RUTHERFORD PD-25-08463,UOF25-5-1,25-08463,5/11/2025,Theft/Shoplifting,Attempt to escape from Custody,Active Resistor,NaN,NaN,TRUE,NaN,Person,19,Hispanic,Male,Used take down on,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [122]:
incidents_path = "./data/incidents.csv"
incidents_df.to_csv(incidents_path, index=False)

# EDA

In [123]:
incidents_df.info()

<class 'pandas.DataFrame'>
Index: 238976 entries, 0 to 5065417
Columns: 176 entries, date to CALI_OFA_USE_VEHICLE
dtypes: datetime64[us](1), float32(19), float64(23), object(6), str(127)
memory usage: 305.4+ MB

In [124]:
info_df = get_info(incidents_df[standard_cols].drop(columns=["incident_id"]))
info_df.style.background_gradient(cmap='viridis')

In [125]:
incidents_df.shape

(238976, 176)

In [126]:
incidents_df[incidents_df["subject_gender"].str.contains(",", regex=False)]

Empty DataFrame
Columns: [date, agency_name, ori, state, location, subject_race, subject_age, subject_gender, force_used, indication_of_injury, incident_id, NJ_Form ID, NJ_County, NJ_Agency Name, NJ_Incident ID, NJ_Report Number, NJ_Incident Case Number, NJ_Incident Date, NJ_Incident Type, NJ_Subject Actions, NJ_Subject Resistance, NJ_Subject Medical Treatment, NJ_Subject Injury Type, NJ_Subject Arrested, NJ_Reason Subject Not Arrested, NJ_Subject Type, NJ_Subject Age, NJ_Subject Race/Ethnicity, NJ_Subject Gender, NJ_Force Type, Ohio_AgencyName, Ohio_IncidentNumber, Ohio_IncidentDate, Ohio_InitialContactCircumstances, Ohio_LocationType, Ohio_SubjectResistanceTypes, Ohio_SubjectArmed/BelievedToBeArmed, Ohio_SubjectRaceEthnicity, Ohio_SubjectGender, Ohio_SubjectInjuries, Ohio_SubjectImpairments, Ohio_OfficerType, Ohio_OfficerResponse/ForceTypes, Ohio_OfficerRaceEthnicity, Ohio_OfficerGender, Ohio_OfficerInjuries, NY_TRI Incident Number, NY_ForceType, NY_Occurrence Date, NY_Incident Pct, NY_Patrol Borough, NY_YearMonthShort, NY_BasisForEncounter, NY_Subject Injury Level, NY_Subject Injured, NY_Age, NY_Subject Race, NY_Subject Gender, NY_Force Against MOS, NY_Subject Used Force, NY_incident_id, NY_Response ID
(5/16/25 File), NY_Agency Name, NY_Incident Date, NY_City/town/village (location Where Incident Occurred), NY_County (location where incident occurred), NY_Circumstance, NY_Officer 1 - Use of Force Type, NY_Officer 1 Age, NY_Officer 1 Sex, NY_Officer 1 Race, NY_Officer 1 Ethnicity, NY_Officer 2 - Use of Force Type, NY_Officer 2 Age, NY_Officer 2 Sex, NY_Officer 2 Race, NY_Officer 2 Ethnicity, NY_Officer 3 - Use of Force Type, NY_Officer 3 Age, NY_Officer 3 Sex, NY_Officer 3 Race, NY_Officer 3 Ethnicity, NY_Officer 4 - Use of Force Type, NY_Officer 4 Age, NY_Officer 4 Sex, NY_Officer 4 Race, NY_Officer 4 Ethnicity, NY_Officer 5 - Use of Force Type, NY_Officer 5 Age, NY_Officer 5 Sex, NY_Officer 5 Race, NY_Officer 5 Ethnicity, NY_Officer 6 - Use of Force Type, NY_Officer 6 Age, NY_Officer 6 Sex, NY_Officer 6 Race, NY_Officer 6 Ethnicity, NY_Officer 7 - Use of Force Type, NY_Officer 7 Age, NY_Officer 7 Sex, ...]
Index: []

In [127]:
incidents_df["state"].value_counts()

state
NY    101466
NJ     97877
CA     36375
OH      3258
Name: count, dtype: int64

In [128]:
incidents_df[lambda x: x.state=="NY"]["force_used"].value_counts()

force_used
Physical Force                                                                                                                                                               48068
Electrical Weapon                                                                                                                                                             8898
Pointed Firearm                                                                                                                                                               7717
Used/Deployed Electronic Control Weapon                                                                                                                                       7571
Used/Deployed Chemical Agent                                                                                                                                                  5027
                                                                                                                                                                             ...
Used/Deployed Chemical Agent | Displayed Chemical Agent Used/Deployed Chemical Agent                                                                                             1
Used/Deployed Chemical Agent | Used/Deployed Chemical Agent    Used/Deployed Electronic Control Weapon                                                                           1
Used/Deployed Electronic Control Weapon | Used/Deployed Electronic Control Weapon | Used/Deployed Chemical Agent    Used/Deployed Electronic Control Weapon                      1
Used/Discharged Firearm | Used/Discharged Firearm | Used/Discharged Firearm | Used/Discharged Firearm | Used/Discharged Firearm | Used/Deployed Electronic Control Weapon        1
Used/Deployed Electronic Control Weapon | Displayed Chemical Agent Used/Deployed Chemical Agent    Used/Deployed Electronic Control Weapon                                       1
Name: count, Length: 818, dtype: int64